import type { CatalogMeal, Diet } from "./types";

const V = ["vegetarian", "eggless_veg"] as Diet[];
const VE = ["vegetarian", "eggless_veg", "vegan"] as Diet[];
const NV = ["nonveg"] as Diet[];
const VG = ["vegetarian"] as Diet[];
const VN = ["vegetarian", "nonveg"] as Diet[];

export const CATALOG_04: CatalogMeal[] = [
  {
    id: "egg-bhurji",
    name: "Masala egg bhurji",
    description: "Indian scrambled eggs with onion and tomato — only when eggs are allowed.",
    cuisine: "Indian",
    mealTypes: ["breakfast", "dinner"],
    diets: VG,
    timeMin: 15,
    uses: ["egg", "eggs", "onion", "tomato", "chili"],
    staples: ["turmeric"],
    ingredients: [
      "4 eggs",
      "onion and tomato",
      "turmeric and chili",
    ],
    steps: [
      "Sauté onion and tomato with spices.",
      "Pour in beaten eggs.",
      "Scramble softly.",
    ],
    notes: "Not for eggless veg. Use besan chilla instead.",
    packable: false,
  },
  {
    id: "omelette",
    name: "Herb omelette",
    description: "A simple folded omelette for vegetarian (with eggs) or non-veg cooks.",
    cuisine: "American",
    mealTypes: ["breakfast"],
    diets: VN,
    timeMin: 10,
    uses: ["egg", "eggs", "cheese", "spinach", "onion"],
    staples: [],
    ingredients: ["3 eggs", "fillings you have", "optional cheese"],
    steps: [
      "Beat eggs with salt.",
      "Cook in a hot pan, add fillings, fold.",
    ],
    notes: "Hidden-egg warning: this is explicitly eggs. Eggless veg should never see it.",
    packable: false,
  },
  {
    id: "tuna-pasta",
    name: "Pantry tuna pasta",
    description: "Non-veg pantry dinner: tuna, tomato, egg-free pasta.",
    cuisine: "Italian",
    mealTypes: ["lunch", "dinner"],
    diets: NV,
    timeMin: 25,
    uses: ["tuna", "tomato", "garlic", "onion"],
    staples: ["egg-free pasta", "olive oil"],
    ingredients: [
      "pasta",
      "1 can tuna",
      "tomatoes and garlic",
    ],
    steps: [
      "Boil pasta.",
      "Make a quick tomato-garlic sauce.",
      "Fold in tuna and pasta.",
    ],
    notes: "Still egg-free pasta. Not for vegetarian diets.",
    packable: false,
  },
  {
    id: "pb-banana",
    name: "Peanut butter banana toast",
    description: "The 5-minute snack that actually fills a kid up.",
    cuisine: "American",
    mealTypes: ["breakfast", "snack", "lunchbox"],
    diets: VE,
    timeMin: 5,
    uses: ["bread", "banana", "peanut butter"],
    staples: ["peanut butter"],
    ingredients: ["bread", "banana", "peanut butter"],
    steps: [
      "Spread peanut butter on bread.",
      "Add banana slices.",
      "Cut into sticks for little hands.",
    ],
    notes: "Packing tip: a little lemon on banana slows browning. Not messy if rolled.",
    packable: true,
  },
  {
    id: "corn-chaat",
    name: "Lemon corn chaat",
    description: "Warm corn with onion, chili, and lemon — Indian snack energy.",
    cuisine: "Indian",
    mealTypes: ["snack", "lunchbox"],
    diets: VE,
    timeMin: 10,
    uses: ["corn", "onion", "lemon", "chili", "tomato"],
    staples: ["chaat masala or cumin"],
    ingredients: ["2 cups corn", "onion", "lemon", "cumin"],
    steps: [
      "Warm corn in a pan.",
      "Toss with onion, lemon, and cumin.",
      "Taste for salt.",
    ],
    notes: "Good at room temp. Skip onion for very young lunchboxes if needed.",
    packable: true,
  },
  {
    id: "soup-tomato",
    name: "Creamy-without-cream tomato soup",
    description: "Blended tomato soup thickened with bread or potato, not cream or egg.",
    cuisine: "American",
    mealTypes: ["lunch", "dinner", "snack"],
    diets: VE,
    timeMin: 25,
    uses: ["tomato", "onion", "garlic", "potato", "bread"],
    staples: ["oregano"],
    ingredients: [
      "tomatoes",
      "onion and garlic",
      "potato or a slice of bread to thicken",
    ],
    steps: [
      "Simmer tomatoes with onion, garlic, and potato.",
      "Blend until smooth.",
      "Season and serve with toast.",
    ],
    notes: "No cream. Grilled cheese on the side if dairy is welcome.",
    packable: false,
  },
  {
    id: "couscous-salad",
    name: "Herb couscous salad",
    description: "Mediterranean lunch that sits happily in a box for hours.",
    cuisine: "Mediterranean",
    mealTypes: ["lunch", "lunchbox"],
    diets: VE,
    timeMin: 15,
    uses: ["cucumber", "tomato", "onion", "lemon", "chickpeas"],
    staples: ["couscous", "olive oil"],
    ingredients: [
      "1 cup couscous",
      "cucumber and tomato",
      "lemon",
      "optional chickpeas",
    ],
    steps: [
      "Steep couscous in boiling water.",
      "Fluff and toss with chopped veg and lemon.",
      "Pack cool.",
    ],
    notes: "If couscous is missing, use leftover rice. Packing tip: extra lemon keeps it bright.",
    packable: true,
  },
  {
    id: "japchae-veg",
    name: "Sweet potato noodle stir",
    description: "Korean-style glass noodles with sesame veg, or spaghetti if that's what you own.",
    cuisine: "Korean",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["spinach", "carrot", "onion", "mushroom", "pepper"],
    staples: ["glass noodles or spaghetti", "soy sauce", "sesame oil"],
    ingredients: [
      "noodles",
      "mixed veg",
      "soy and sesame",
    ],
    steps: [
      "Cook noodles.",
      "Stir-fry veg.",
      "Toss together with soy and sesame.",
    ],
    notes: "No egg garnish. Spaghetti is an honest substitute for dangmyeon.",
    packable: false,
  },
  {
    id: "okonomiyaki-eggless",
    name: "Cabbage skillet pancake",
    description: "Okonomiyaki spirit: cabbage bound with flour and mashed potato, not eggs.",
    cuisine: "Japanese",
    mealTypes: ["lunch", "dinner", "snack"],
    diets: VE,
    timeMin: 25,
    uses: ["cabbage", "potato", "carrot", "onion", "flour"],
    staples: ["flour", "soy sauce"],
    ingredients: [
      "3 cups shredded cabbage",
      "1 mashed potato or 3 tbsp flour extra",
      "onion",
      "soy for brushing",
    ],
    steps: [
      "Mix cabbage with mash/flour and salt.",
      "Press into a hot pan; cook both sides until set.",
      "Brush with soy.",
    ],
    notes: "Potato starch-style binding instead of eggs. Flip carefully.",
    packable: false,
  },
  {
    id: "veg-biryani",
    name: "One-pot vegetable biryani",
    description: "Layered rice with potatoes, peas, and whole-spice warmth — no egg wash on the crust.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["rice", "potato", "peas", "onion", "yogurt", "carrot"],
    staples: ["biryani masala or garam masala", "bay leaf"],
    ingredients: ["1.5 cups rice", "potato and peas", "onion", "yogurt splash", "garam masala"],
    steps: ["Fry onion until gold.", "Add veg and spices.", "Steam rice on top until fluffy."],
    notes: "Yogurt is optional. No boiled-egg garnish.",
    packable: false,
  }
];
