import type { CatalogMeal, Diet } from "./types";

const V = ["vegetarian", "eggless_veg"] as Diet[];
const VE = ["vegetarian", "eggless_veg", "vegan"] as Diet[];
const NV = ["nonveg"] as Diet[];
const VG = ["vegetarian"] as Diet[];
const VN = ["vegetarian", "nonveg"] as Diet[];

export const CATALOG_B: CatalogMeal[] = [
  {
    id: "chicken-rice",
    name: "Lemon garlic chicken and rice",
    description: "One-pan chicken thighs with rice for non-veg nights under 40 minutes.",
    cuisine: "American",
    mealTypes: ["dinner"],
    diets: NV,
    timeMin: 40,
    uses: ["chicken", "rice", "lemon", "garlic", "onion"],
    staples: ["rice", "paprika"],
    ingredients: [
      "4 chicken thighs",
      "1 cup rice",
      "lemon and garlic",
      "onion",
    ],
    steps: [
      "Brown chicken; set aside.",
      "Sauté onion and garlic, add rice and water.",
      "Nestle chicken back, cover, cook 20 minutes.",
    ],
    notes: "Weeknight-timed. Use the lemon you already scanned.",
    packable: false,
  },
  {
    id: "egg-bhurji",
    name: "Masala egg bhurji",
    description: "Indian scrambled eggs with onion and tomato — only when eggs are allowed.",
    cuisine: "Indian",
    mealTypes: ["breakfast", "dinner"],
    diets: VG,
    timeMin: 15,
    uses: ["egg", "eggs", "onion", "tomato", "chili"],
    staples: ["turmeric"],
    ingredients: [
      "4 eggs",
      "onion and tomato",
      "turmeric and chili",
    ],
    steps: [
      "Sauté onion and tomato with spices.",
      "Pour in beaten eggs.",
      "Scramble softly.",
    ],
    notes: "Not for eggless veg. Use besan chilla instead.",
    packable: false,
  },
  {
    id: "omelette",
    name: "Herb omelette",
    description: "A simple folded omelette for vegetarian (with eggs) or non-veg cooks.",
    cuisine: "American",
    mealTypes: ["breakfast"],
    diets: VN,
    timeMin: 10,
    uses: ["egg", "eggs", "cheese", "spinach", "onion"],
    staples: [],
    ingredients: ["3 eggs", "fillings you have", "optional cheese"],
    steps: [
      "Beat eggs with salt.",
      "Cook in a hot pan, add fillings, fold.",
    ],
    notes: "Hidden-egg warning: this is explicitly eggs. Eggless veg should never see it.",
    packable: false,
  },
  {
    id: "tuna-pasta",
    name: "Pantry tuna pasta",
    description: "Non-veg pantry dinner: tuna, tomato, egg-free pasta.",
    cuisine: "Italian",
    mealTypes: ["lunch", "dinner"],
    diets: NV,
    timeMin: 25,
    uses: ["tuna", "tomato", "garlic", "onion"],
    staples: ["egg-free pasta", "olive oil"],
    ingredients: [
      "pasta",
      "1 can tuna",
      "tomatoes and garlic",
    ],
    steps: [
      "Boil pasta.",
      "Make a quick tomato-garlic sauce.",
      "Fold in tuna and pasta.",
    ],
    notes: "Still egg-free pasta. Not for vegetarian diets.",
    packable: false,
  },
  {
    id: "pb-banana",
    name: "Peanut butter banana toast",
    description: "The 5-minute snack that actually fills a kid up.",
    cuisine: "American",
    mealTypes: ["breakfast", "snack", "lunchbox"],
    diets: VE,
    timeMin: 5,
    uses: ["bread", "banana", "peanut butter"],
    staples: ["peanut butter"],
    ingredients: ["bread", "banana", "peanut butter"],
    steps: [
      "Spread peanut butter on bread.",
      "Add banana slices.",
      "Cut into sticks for little hands.",
    ],
    notes: "Packing tip: a little lemon on banana slows browning. Not messy if rolled.",
    packable: true,
  },
  {
    id: "corn-chaat",
    name: "Lemon corn chaat",
    description: "Warm corn with onion, chili, and lemon — Indian snack energy.",
    cuisine: "Indian",
    mealTypes: ["snack", "lunchbox"],
    diets: VE,
    timeMin: 10,
    uses: ["corn", "onion", "lemon", "chili", "tomato"],
    staples: ["chaat masala or cumin"],
    ingredients: ["2 cups corn", "onion", "lemon", "cumin"],
    steps: [
      "Warm corn in a pan.",
      "Toss with onion, lemon, and cumin.",
      "Taste for salt.",
    ],
    notes: "Good at room temp. Skip onion for very young lunchboxes if needed.",
    packable: true,
  },
  {
    id: "soup-tomato",
    name: "Creamy-without-cream tomato soup",
    description: "Blended tomato soup thickened with bread or potato, not cream or egg.",
    cuisine: "American",
    mealTypes: ["lunch", "dinner", "snack"],
    diets: VE,
    timeMin: 25,
    uses: ["tomato", "onion", "garlic", "potato", "bread"],
    staples: ["oregano"],
    ingredients: [
      "tomatoes",
      "onion and garlic",
      "potato or a slice of bread to thicken",
    ],
    steps: [
      "Simmer tomatoes with onion, garlic, and potato.",
      "Blend until smooth.",
      "Season and serve with toast.",
    ],
    notes: "No cream. Grilled cheese on the side if dairy is welcome.",
    packable: false,
  },
  {
    id: "couscous-salad",
    name: "Herb couscous salad",
    description: "Mediterranean lunch that sits happily in a box for hours.",
    cuisine: "Mediterranean",
    mealTypes: ["lunch", "lunchbox"],
    diets: VE,
    timeMin: 15,
    uses: ["cucumber", "tomato", "onion", "lemon", "chickpeas"],
    staples: ["couscous", "olive oil"],
    ingredients: [
      "1 cup couscous",
      "cucumber and tomato",
      "lemon",
      "optional chickpeas",
    ],
    steps: [
      "Steep couscous in boiling water.",
      "Fluff and toss with chopped veg and lemon.",
      "Pack cool.",
    ],
    notes: "If couscous is missing, use leftover rice. Packing tip: extra lemon keeps it bright.",
    packable: true,
  },
  {
    id: "japchae-veg",
    name: "Sweet potato noodle stir",
    description: "Korean-style glass noodles with sesame veg, or spaghetti if that's what you own.",
    cuisine: "Korean",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["spinach", "carrot", "onion", "mushroom", "pepper"],
    staples: ["glass noodles or spaghetti", "soy sauce", "sesame oil"],
    ingredients: [
      "noodles",
      "mixed veg",
      "soy and sesame",
    ],
    steps: [
      "Cook noodles.",
      "Stir-fry veg.",
      "Toss together with soy and sesame.",
    ],
    notes: "No egg garnish. Spaghetti is an honest substitute for dangmyeon.",
    packable: false,
  },
  {
    id: "okonomiyaki-eggless",
    name: "Cabbage skillet pancake",
    description: "Okonomiyaki spirit: cabbage bound with flour and mashed potato, not eggs.",
    cuisine: "Japanese",
    mealTypes: ["lunch", "dinner", "snack"],
    diets: VE,
    timeMin: 25,
    uses: ["cabbage", "potato", "carrot", "onion", "flour"],
    staples: ["flour", "soy sauce"],
    ingredients: [
      "3 cups shredded cabbage",
      "1 mashed potato or 3 tbsp flour extra",
      "onion",
      "soy for brushing",
    ],
    steps: [
      "Mix cabbage with mash/flour and salt.",
      "Press into a hot pan; cook both sides until set.",
      "Brush with soy.",
    ],
    notes: "Potato starch-style binding instead of eggs. Flip carefully.",
    packable: false,
  },
  {
    id: "veg-biryani",
    name: "One-pot vegetable biryani",
    description: "Layered rice with potatoes, peas, and whole-spice warmth — no egg wash on the crust.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["rice", "potato", "peas", "onion", "yogurt", "carrot"],
    staples: ["biryani masala or garam masala", "bay leaf"],
    ingredients: ["1.5 cups rice", "potato and peas", "onion", "yogurt splash", "garam masala"],
    steps: ["Fry onion until gold.", "Add veg and spices.", "Steam rice on top until fluffy."],
    notes: "Yogurt is optional. No boiled-egg garnish.",
    packable: false,
  },
  {
    id: "rajma",
    name: "Tomato rajma",
    description: "Kidney beans in a slow onion-tomato gravy. Rice on the side.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["beans", "kidney beans", "rajma", "onion", "tomato", "garlic"],
    staples: ["rajma or canned kidney beans", "garam masala"],
    ingredients: ["2 cups kidney beans", "onion and tomato", "garlic", "garam masala"],
    steps: ["Sauté onion and garlic.", "Add tomato and spices.", "Simmer beans 15 minutes."],
    notes: "Canned beans keep it weeknight. Fully eggless.",
    packable: false,
  },
  {
    id: "veg-korma",
    name: "Mild coconut korma",
    description: "Soft vegetables in a gentle coconut gravy — kid-friendly spice.",
    cuisine: "Indian",
    mealTypes: ["dinner"],
    diets: VE,
    timeMin: 35,
    uses: ["potato", "carrot", "peas", "onion", "spinach", "paneer"],
    staples: ["coconut milk", "garam masala"],
    ingredients: ["mixed veg", "onion", "coconut milk", "garam masala"],
    steps: ["Sauté onion.", "Add veg and coconut milk.", "Simmer until the potato yields."],
    notes: "No cream, no nut paste required if coconut milk is there.",
    packable: false,
  },
  {
    id: "mushroom-masala",
    name: "Bhuna mushroom masala",
    description: "Mushrooms cooked down with onion, tomato, and garam masala.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 25,
    uses: ["mushroom", "onion", "tomato", "garlic", "peas"],
    staples: ["garam masala", "cumin"],
    ingredients: ["mushrooms", "onion and tomato", "garlic", "garam masala"],
    steps: ["Sear mushrooms until they give up water.", "Add onion, tomato, spices.", "Cook until thick."],
    notes: "Works as a wrap filling the next day.",
    packable: false,
  },
  {
    id: "baingan",
    name: "Smoky baingan mash",
    description: "Roasted eggplant mashed with onion, tomato, and lemon.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 35,
    uses: ["eggplant", "onion", "tomato", "garlic", "lemon"],
    staples: ["cumin"],
    ingredients: ["1 large eggplant", "onion and tomato", "garlic", "lemon"],
    steps: ["Roast or pan-char eggplant until collapsed.", "Mash with sautéed onion and tomato.", "Finish with lemon."],
    notes: "Bread or rice. No yogurt required.",
    packable: false,
  },
  {
    id: "sambar-veg",
    name: "Weeknight sambar",
    description: "Lentil-tamarind stew with whatever vegetables are on the way out.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["lentils", "dal", "onion", "tomato", "carrot", "spinach"],
    staples: ["sambar powder or cumin+coriander", "tamarind or lemon"],
    ingredients: ["lentils", "mixed veg", "tomato", "sambar powder or lemon"],
    steps: ["Cook lentils until soft.", "Add veg and spice.", "Sour with lemon if tamarind is missing."],
    notes: "Lemon stands in for tamarind. Eggless, of course.",
    packable: false,
  },
  {
    id: "poha",
    name: "Kanda poha",
    description: "Flattened rice with onion, mustard seed, and lemon — breakfast or light dinner.",
    cuisine: "Indian",
    mealTypes: ["breakfast", "snack", "dinner"],
    diets: VE,
    timeMin: 15,
    uses: ["onion", "potato", "peas", "lemon", "chili"],
    staples: ["poha (flattened rice)", "mustard seeds", "turmeric"],
    ingredients: ["2 cups poha", "onion", "optional potato", "lemon", "turmeric"],
    steps: ["Rinse poha and drain.", "Pop mustard seeds; sauté onion.", "Toss poha with turmeric and lemon."],
    notes: "If poha is missing, leftover rice upma is the honest swap.",
    packable: false,
  },
  {
    id: "pav-style-mash",
    name: "Pav-style potato masala",
    description: "Street-style spiced potatoes piled on bread or eaten with a spoon.",
    cuisine: "Indian",
    mealTypes: ["breakfast", "lunch", "dinner", "snack"],
    diets: VE,
    timeMin: 25,
    uses: ["potato", "onion", "bread", "peas", "lemon"],
    staples: ["mustard seeds", "turmeric"],
    ingredients: ["potatoes", "onion", "bread", "turmeric", "lemon"],
    steps: ["Boil and roughly mash potatoes.", "Sauté onion and spices.", "Fold together and pile on toast."],
    notes: "No pav? Any bread. No egg wash on the bun.",
    packable: true,
  },
  {
    id: "aglio-spinaci",
    name: "Spinach aglio e olio",
    description: "Garlic oil pasta with a heap of greens from the fridge.",
    cuisine: "Italian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 20,
    uses: ["spinach", "garlic", "chili", "lemon"],
    staples: ["egg-free pasta", "olive oil", "chili flakes"],
    ingredients: ["pasta", "lots of spinach", "garlic", "chili flakes", "lemon"],
    steps: ["Boil egg-free pasta.", "Sizzle garlic and chili in oil.", "Wilt spinach and toss pasta in."],
    notes: "Confirm egg-free pasta. Lemon instead of cheese for vegan.",
    packable: false,
  },
  {
    id: "white-bean-stew",
    name: "Rosemary white bean stew",
    description: "A Tuscan-leaning pot of beans, tomato, and greens.",
    cuisine: "Italian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["beans", "tomato", "spinach", "onion", "garlic", "carrot"],
    staples: ["dried rosemary or oregano"],
    ingredients: ["beans", "tomato", "greens", "onion", "garlic"],
    steps: ["Sauté onion, carrot, garlic.", "Add tomato and beans.", "Simmer and fold in greens."],
    notes: "Bread for dipping. No parmesan required.",
    packable: false,
  },
  {
    id: "elote-bowl",
    name: "Chili-lime corn bowl",
    description: "Warm corn, chili, lime, and whatever cheese you have — no mayo.",
    cuisine: "Mexican",
    mealTypes: ["lunch", "snack", "dinner"],
    diets: V,
    timeMin: 15,
    uses: ["corn", "lime", "lemon", "chili", "cheese", "onion"],
    staples: ["chili powder"],
    ingredients: ["corn", "lime", "chili powder", "optional cheese"],
    steps: ["Warm corn in a pan.", "Toss with lime and chili.", "Crumble cheese on top if dairy is welcome."],
    notes: "Yogurt instead of mayo. Vegan: skip cheese.",
    packable: true,
  },
  {
    id: "enchilada-skillet",
    name: "Bean enchilada skillet",
    description: "Tortillas, beans, and salsa baked in one pan.",
    cuisine: "Mexican",
    mealTypes: ["dinner"],
    diets: V,
    timeMin: 35,
    uses: ["beans", "tortilla", "tomato", "cheese", "onion", "pepper"],
    staples: ["chili powder", "cumin"],
    ingredients: ["beans", "tortillas", "tomato salsa", "cheese", "onion"],
    steps: ["Sauté onion and beans with chili.", "Layer torn tortillas and tomato.", "Melt cheese on top."],
    notes: "No egg wash. Corn tortillas if you have them.",
    packable: false,
  },
  {
    id: "black-bean-soup",
    name: "Cumin black bean soup",
    description: "Blended or chunky, cheap, and better the next day.",
    cuisine: "Mexican",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["beans", "onion", "garlic", "tomato", "pepper", "lime"],
    staples: ["cumin"],
    ingredients: ["2 cans black beans", "onion and garlic", "cumin", "lime"],
    steps: ["Sauté onion and garlic.", "Add beans, cumin, water.", "Simmer and mash some of the beans."],
    notes: "Lime at the end. Freeze leftovers.",
    packable: false,
  },
  {
    id: "ginger-tofu-noodles",
    name: "Ginger tofu noodles",
    description: "Chewy noodles, crispy tofu, a lot of ginger from the counter.",
    cuisine: "Chinese",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 25,
    uses: ["tofu", "ginger", "garlic", "cabbage", "carrot", "scallion"],
    staples: ["noodles", "soy sauce"],
    ingredients: ["noodles", "tofu", "ginger and garlic", "cabbage", "soy"],
    steps: ["Pan-fry tofu.", "Stir-fry ginger, garlic, veg.", "Toss noodles and soy."],
    notes: "Spaghetti if you don't have Chinese noodles. No egg.",
    packable: false,
  },
  {
    id: "hot-sour-soup",
    name: "Hot and sour mushroom soup",
    description: "A sharp, peppery bowl that uses up mushrooms and tofu.",
    cuisine: "Chinese",
    mealTypes: ["lunch", "dinner", "snack"],
    diets: VE,
    timeMin: 20,
    uses: ["mushroom", "tofu", "cabbage", "carrot", "ginger"],
    staples: ["soy sauce", "vinegar", "white pepper"],
    ingredients: ["mushrooms", "tofu", "vinegar", "soy", "ginger"],
    steps: ["Simmer ginger and mushrooms.", "Add tofu and soy.", "Sharpen with vinegar and pepper."],
    notes: "No egg ribbon. Cornstarch optional for body.",
    packable: false,
  },
  {
    id: "basil-tofu",
    name: "Holy-basil style tofu",
    description: "Thai chili-basil stir-fry with tofu instead of minced meat.",
    cuisine: "Thai",
    mealTypes: ["dinner"],
    diets: VE,
    timeMin: 20,
    uses: ["tofu", "pepper", "onion", "garlic", "basil", "chili"],
    staples: ["soy sauce", "rice"],
    ingredients: ["tofu", "pepper and onion", "garlic", "basil if you have it", "soy"],
    steps: ["Crumble and fry tofu.", "Add garlic, chili, veg.", "Finish with soy and torn basil."],
    notes: "Spinach stands in for holy basil. Serve over rice.",
    packable: false,
  },
  {
    id: "tom-yum-veg",
    name: "Quick lemongrass sour soup",
    description: "A tom-yum cousin with lime, chili, and mushrooms.",
    cuisine: "Thai",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 25,
    uses: ["mushroom", "lime", "lemon", "tomato", "chili", "tofu"],
    staples: ["lemongrass or lime leaves", "soy sauce"],
    ingredients: ["mushrooms", "tomato", "lime", "chili", "tofu"],
    steps: ["Simmer aromatics in water.", "Add mushroom and tomato.", "Finish with lime; add tofu."],
    notes: "No fish sauce. Lemon if lime is gone.",
    packable: false,
  },
  {
    id: "teriyaki-veg",
    name: "Teriyaki roasted veg rice",
    description: "Sheet-pan vegetables glazed with soy and a pinch of sugar over rice.",
    cuisine: "Japanese",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 35,
    uses: ["broccoli", "pepper", "carrot", "tofu", "onion", "rice"],
    staples: ["soy sauce", "rice"],
    ingredients: ["mixed veg", "tofu", "soy", "pinch of sugar", "rice"],
    steps: ["Toss veg and tofu with soy and sugar.", "Roast hot until edges catch.", "Serve over rice."],
    notes: "No mirin needed. Honey is fine if not vegan.",
    packable: false,
  },
  {
    id: "udon-peanut",
    name: "Sesame udon bowl",
    description: "Thick noodles, sesame, cucumber — cold or warm.",
    cuisine: "Japanese",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 20,
    uses: ["cucumber", "carrot", "scallion", "tofu"],
    staples: ["udon or spaghetti", "soy sauce", "sesame oil"],
    ingredients: ["noodles", "cucumber", "soy and sesame", "optional tofu"],
    steps: ["Cook noodles.", "Shake soy and sesame as a dressing.", "Toss with cucumber and tofu."],
    notes: "Spaghetti is an honest udon stand-in.",
    packable: true,
  },
  {
    id: "spanakorizo",
    name: "Lemon spinach rice",
    description: "Greek spinach rice with a lot of lemon — a full plate, not a side.",
    cuisine: "Mediterranean",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["spinach", "rice", "onion", "lemon", "tomato"],
    staples: ["rice", "olive oil", "dill or oregano"],
    ingredients: ["rice", "a lot of spinach", "onion", "lemon"],
    steps: ["Sauté onion.", "Add rice, water, spinach.", "Finish with lots of lemon."],
    notes: "Feta if you have it and dairy is allowed.",
    packable: false,
  },
  {
    id: "gigantes",
    name: "Tomato baked beans",
    description: "Mediterranean giant-bean energy with ordinary canned beans.",
    cuisine: "Mediterranean",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 35,
    uses: ["beans", "tomato", "onion", "garlic", "spinach"],
    staples: ["oregano", "olive oil"],
    ingredients: ["beans", "tomato", "onion", "oregano"],
    steps: ["Sauté onion and garlic.", "Add tomato, oregano, beans.", "Simmer until saucy."],
    notes: "Oven if you have time; stove is fine.",
    packable: false,
  },
  {
    id: "mujaddara-bowl",
    name: "Herbed lentil rice bowl",
    description: "A faster cousin of mujaddara with lemon and leftover greens.",
    cuisine: "Middle Eastern",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["lentils", "rice", "onion", "spinach", "lemon"],
    staples: ["cumin"],
    ingredients: ["lentils", "rice", "onion", "cumin", "lemon"],
    steps: ["Cook lentils and rice (together if you're brave).", "Fry onions.", "Pile with lemon."],
    notes: "Repeats well across a week without wasting spices.",
    packable: false,
  },
  {
    id: "fattoush-box",
    name: "Broken-bread fattoush",
    description: "Tomato-cucumber salad with toasted leftover bread.",
    cuisine: "Middle Eastern",
    mealTypes: ["lunch", "lunchbox"],
    diets: VE,
    timeMin: 15,
    uses: ["tomato", "cucumber", "onion", "bread", "lemon", "lettuce"],
    staples: ["sumac or lemon zest", "olive oil"],
    ingredients: ["tomato and cucumber", "stale bread", "lemon", "onion"],
    steps: ["Toast bread pieces.", "Chop salad.", "Toss with lemon just before eating."],
    notes: "Packing tip: keep bread dry until lunch.",
    packable: true,
  },
  {
    id: "doenjang-stew",
    name: "Soft tofu stew",
    description: "A Korean-leaning soybean stew with whatever veg is tired.",
    cuisine: "Korean",
    mealTypes: ["dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["tofu", "zucchini", "onion", "mushroom", "spinach"],
    staples: ["doenjang or miso", "gochugaru or chili flakes"],
    ingredients: ["tofu", "onion and mushroom", "miso or doenjang", "chili flakes"],
    steps: ["Simmer onion and mushroom.", "Whisk in miso off a rolling boil.", "Add tofu gently."],
    notes: "Miso is the pantry stand-in for doenjang.",
    packable: false,
  },
  {
    id: "scallion-pancake",
    name: "Crispy scallion pancakes",
    description: "Flour, water, scallion or onion — no egg in the dough.",
    cuisine: "Chinese",
    mealTypes: ["snack", "breakfast", "dinner"],
    diets: VE,
    timeMin: 25,
    uses: ["scallion", "onion", "flour"],
    staples: ["flour", "sesame oil"],
    ingredients: ["flour", "hot water", "scallion or onion", "salt"],
    steps: ["Make a soft dough.", "Roll with chopped scallion.", "Pan-fry until blistered."],
    notes: "Dipping soy on the side. Fully eggless.",
    packable: false,
  },
  {
    id: "sloppy-lentil",
    name: "Sloppy lentil toast",
    description: "American diner energy, vegetarian, piled on bread.",
    cuisine: "American",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["lentils", "onion", "tomato", "pepper", "bread"],
    staples: ["ketchup or tomato paste", "chili powder"],
    ingredients: ["lentils", "onion and pepper", "tomato", "bread"],
    steps: ["Sauté onion and pepper.", "Add lentils, tomato, chili.", "Spoon onto toast."],
    notes: "No mystery meat. Kids usually approve.",
    packable: false,
  },
  {
    id: "loaded-potato",
    name: "Loaded skillet potatoes",
    description: "Crisp potatoes with yogurt, cheese, and whatever veg is left.",
    cuisine: "American",
    mealTypes: ["breakfast", "dinner"],
    diets: V,
    timeMin: 30,
    uses: ["potato", "yogurt", "cheese", "onion", "spinach", "pepper"],
    staples: ["paprika"],
    ingredients: ["potatoes", "onion", "yogurt or cheese", "paprika"],
    steps: ["Pan-fry potatoes until crisp.", "Add onion and greens.", "Finish with yogurt or cheese."],
    notes: "No sour cream required. Vegan: skip dairy, add lemon.",
    packable: false,
  },
  {
    id: "chicken-wrap",
    name: "Lemon chicken lunch wrap",
    description: "Cold leftover chicken, cucumber, and bread — packs without reheating.",
    cuisine: "American",
    mealTypes: ["lunch", "lunchbox"],
    diets: NV,
    timeMin: 15,
    uses: ["chicken", "cucumber", "bread", "tortilla", "yogurt", "lettuce"],
    staples: ["wraps or bread"],
    ingredients: ["cooked chicken", "cucumber", "bread or wrap", "yogurt smear"],
    steps: ["Slice leftover chicken.", "Spread yogurt, add cucumber.", "Wrap tight and pack."],
    notes: "Packing tip: wrap in parchment so it doesn't go soggy. Cool chicken first.",
    packable: true,
  },
  {
    id: "tuna-box",
    name: "Tuna cucumber sandwich box",
    description: "Tuna mashed with yogurt (not mayo), cucumber, bread. Fine at room temp for hours.",
    cuisine: "American",
    mealTypes: ["lunch", "lunchbox"],
    diets: NV,
    timeMin: 10,
    uses: ["tuna", "cucumber", "bread", "yogurt", "lemon"],
    staples: ["canned tuna"],
    ingredients: ["canned tuna", "yogurt", "cucumber", "bread", "lemon"],
    steps: ["Mash tuna with yogurt and lemon.", "Layer with cucumber on bread.", "Pack veg sticks on the side."],
    notes: "Yogurt instead of mayo. Packing tip: keep filling and bread apart if the morning is humid.",
    packable: true,
  },
];
