import type { CatalogMeal, Diet } from "./types";

const V = ["vegetarian", "eggless_veg"] as Diet[];
const VE = ["vegetarian", "eggless_veg", "vegan"] as Diet[];
const NV = ["nonveg"] as Diet[];
const VG = ["vegetarian"] as Diet[];
const VN = ["vegetarian", "nonveg"] as Diet[];

export const CATALOG_06: CatalogMeal[] = [
  {
    id: "enchilada-skillet",
    name: "Bean enchilada skillet",
    description: "Tortillas, beans, and salsa baked in one pan.",
    cuisine: "Mexican",
    mealTypes: ["dinner"],
    diets: V,
    timeMin: 35,
    uses: ["beans", "tortilla", "tomato", "cheese", "onion", "pepper"],
    staples: ["chili powder", "cumin"],
    ingredients: ["beans", "tortillas", "tomato salsa", "cheese", "onion"],
    steps: ["Sauté onion and beans with chili.", "Layer torn tortillas and tomato.", "Melt cheese on top."],
    notes: "No egg wash. Corn tortillas if you have them.",
    packable: false,
  },
  {
    id: "black-bean-soup",
    name: "Cumin black bean soup",
    description: "Blended or chunky, cheap, and better the next day.",
    cuisine: "Mexican",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["beans", "onion", "garlic", "tomato", "pepper", "lime"],
    staples: ["cumin"],
    ingredients: ["2 cans black beans", "onion and garlic", "cumin", "lime"],
    steps: ["Sauté onion and garlic.", "Add beans, cumin, water.", "Simmer and mash some of the beans."],
    notes: "Lime at the end. Freeze leftovers.",
    packable: false,
  },
  {
    id: "ginger-tofu-noodles",
    name: "Ginger tofu noodles",
    description: "Chewy noodles, crispy tofu, a lot of ginger from the counter.",
    cuisine: "Chinese",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 25,
    uses: ["tofu", "ginger", "garlic", "cabbage", "carrot", "scallion"],
    staples: ["noodles", "soy sauce"],
    ingredients: ["noodles", "tofu", "ginger and garlic", "cabbage", "soy"],
    steps: ["Pan-fry tofu.", "Stir-fry ginger, garlic, veg.", "Toss noodles and soy."],
    notes: "Spaghetti if you don't have Chinese noodles. No egg.",
    packable: false,
  },
  {
    id: "hot-sour-soup",
    name: "Hot and sour mushroom soup",
    description: "A sharp, peppery bowl that uses up mushrooms and tofu.",
    cuisine: "Chinese",
    mealTypes: ["lunch", "dinner", "snack"],
    diets: VE,
    timeMin: 20,
    uses: ["mushroom", "tofu", "cabbage", "carrot", "ginger"],
    staples: ["soy sauce", "vinegar", "white pepper"],
    ingredients: ["mushrooms", "tofu", "vinegar", "soy", "ginger"],
    steps: ["Simmer ginger and mushrooms.", "Add tofu and soy.", "Sharpen with vinegar and pepper."],
    notes: "No egg ribbon. Cornstarch optional for body.",
    packable: false,
  },
  {
    id: "basil-tofu",
    name: "Holy-basil style tofu",
    description: "Thai chili-basil stir-fry with tofu instead of minced meat.",
    cuisine: "Thai",
    mealTypes: ["dinner"],
    diets: VE,
    timeMin: 20,
    uses: ["tofu", "pepper", "onion", "garlic", "basil", "chili"],
    staples: ["soy sauce", "rice"],
    ingredients: ["tofu", "pepper and onion", "garlic", "basil if you have it", "soy"],
    steps: ["Crumble and fry tofu.", "Add garlic, chili, veg.", "Finish with soy and torn basil."],
    notes: "Spinach stands in for holy basil. Serve over rice.",
    packable: false,
  },
  {
    id: "tom-yum-veg",
    name: "Quick lemongrass sour soup",
    description: "A tom-yum cousin with lime, chili, and mushrooms.",
    cuisine: "Thai",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 25,
    uses: ["mushroom", "lime", "lemon", "tomato", "chili", "tofu"],
    staples: ["lemongrass or lime leaves", "soy sauce"],
    ingredients: ["mushrooms", "tomato", "lime", "chili", "tofu"],
    steps: ["Simmer aromatics in water.", "Add mushroom and tomato.", "Finish with lime; add tofu."],
    notes: "No fish sauce. Lemon if lime is gone.",
    packable: false,
  },
  {
    id: "teriyaki-veg",
    name: "Teriyaki roasted veg rice",
    description: "Sheet-pan vegetables glazed with soy and a pinch of sugar over rice.",
    cuisine: "Japanese",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 35,
    uses: ["broccoli", "pepper", "carrot", "tofu", "onion", "rice"],
    staples: ["soy sauce", "rice"],
    ingredients: ["mixed veg", "tofu", "soy", "pinch of sugar", "rice"],
    steps: ["Toss veg and tofu with soy and sugar.", "Roast hot until edges catch.", "Serve over rice."],
    notes: "No mirin needed. Honey is fine if not vegan.",
    packable: false,
  },
  {
    id: "udon-peanut",
    name: "Sesame udon bowl",
    description: "Thick noodles, sesame, cucumber — cold or warm.",
    cuisine: "Japanese",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 20,
    uses: ["cucumber", "carrot", "scallion", "tofu"],
    staples: ["udon or spaghetti", "soy sauce", "sesame oil"],
    ingredients: ["noodles", "cucumber", "soy and sesame", "optional tofu"],
    steps: ["Cook noodles.", "Shake soy and sesame as a dressing.", "Toss with cucumber and tofu."],
    notes: "Spaghetti is an honest udon stand-in.",
    packable: true,
  },
  {
    id: "spanakorizo",
    name: "Lemon spinach rice",
    description: "Greek spinach rice with a lot of lemon — a full plate, not a side.",
    cuisine: "Mediterranean",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["spinach", "rice", "onion", "lemon", "tomato"],
    staples: ["rice", "olive oil", "dill or oregano"],
    ingredients: ["rice", "a lot of spinach", "onion", "lemon"],
    steps: ["Sauté onion.", "Add rice, water, spinach.", "Finish with lots of lemon."],
    notes: "Feta if you have it and dairy is allowed.",
    packable: false,
  },
  {
    id: "gigantes",
    name: "Tomato baked beans",
    description: "Mediterranean giant-bean energy with ordinary canned beans.",
    cuisine: "Mediterranean",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 35,
    uses: ["beans", "tomato", "onion", "garlic", "spinach"],
    staples: ["oregano", "olive oil"],
    ingredients: ["beans", "tomato", "onion", "oregano"],
    steps: ["Sauté onion and garlic.", "Add tomato, oregano, beans.", "Simmer until saucy."],
    notes: "Oven if you have time; stove is fine.",
    packable: false,
  }
];
