import type { CatalogMeal, Diet } from "./types";

const V = ["vegetarian", "eggless_veg"] as Diet[];
const VE = ["vegetarian", "eggless_veg", "vegan"] as Diet[];
const NV = ["nonveg"] as Diet[];
const VG = ["vegetarian"] as Diet[];
const VN = ["vegetarian", "nonveg"] as Diet[];

export const CATALOG_03: CatalogMeal[] = [
  {
    id: "kimchi-fried-rice",
    name: "Kimchi fried rice (tofu)",
    description: "Tangy, spicy fried rice. Tofu instead of spam or egg.",
    cuisine: "Korean",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 20,
    uses: ["rice", "kimchi", "onion", "tofu", "scallion"],
    staples: ["gochujang", "soy sauce"],
    ingredients: [
      "3 cups cooked rice",
      "1 cup kimchi, chopped",
      "tofu cubes",
      "soy sauce",
    ],
    steps: [
      "Sauté kimchi and onion.",
      "Add tofu, then rice.",
      "Season with soy and a dab of gochujang.",
    ],
    notes: "If kimchi is not in the fridge photo, we'll ask. Vegan kimchi if you avoid fish sauce.",
    packable: false,
  },
  {
    id: "mejadra",
    name: "Lentils and rice with onions",
    description: "A Middle Eastern pot of lentils, rice, and sweet fried onions.",
    cuisine: "Middle Eastern",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["lentils", "rice", "onion"],
    staples: ["cumin", "cinnamon"],
    ingredients: [
      "1 cup lentils",
      "1 cup rice",
      "2 onions",
      "cumin",
    ],
    steps: [
      "Cook lentils until almost tender.",
      "Add rice, water, and cumin; steam until done.",
      "Fry onions until dark gold and pile on top.",
    ],
    notes: "Budget hero. Repeats well across a week without feeling sad.",
    packable: false,
  },
  {
    id: "mac-cheese",
    name: "Stovetop mac and cheese",
    description: "One-pot pasta with a simple cheese sauce — egg-free pasta only.",
    cuisine: "American",
    mealTypes: ["lunch", "dinner"],
    diets: V,
    timeMin: 20,
    uses: ["cheese", "milk", "butter"],
    staples: ["short pasta (egg-free)", "flour"],
    ingredients: [
      "250 g short pasta",
      "1 cup milk",
      "1 cup grated cheese",
      "1 tbsp flour",
    ],
    steps: [
      "Cook pasta; save a little water.",
      "Make a quick flour-milk sauce.",
      "Melt in cheese and toss pasta.",
    ],
    notes: "Confirm egg-free pasta. Mustard pinch if you have it, never egg yolk.",
    packable: false,
  },
  {
    id: "pancake-banana",
    name: "Banana skillet pancakes",
    description: "Eggless pancakes using banana and flour — weekend-feeling breakfast.",
    cuisine: "American",
    mealTypes: ["breakfast"],
    diets: V,
    timeMin: 20,
    uses: ["banana", "milk", "flour"],
    staples: ["flour", "baking powder"],
    ingredients: [
      "1 ripe banana",
      "1 cup flour",
      "1 cup milk",
      "1 tsp baking powder",
    ],
    steps: [
      "Mash banana and whisk with milk, flour, and baking powder.",
      "Cook spoons of batter in a lightly oiled pan.",
      "Flip when bubbles set.",
    ],
    notes: "Banana binds instead of egg. Vegan with oat milk.",
    packable: false,
  },
  {
    id: "idli-upma-style",
    name: "Savory leftover rice upma",
    description: "South-Indian-leaning stir of leftover rice with mustard seeds and veg.",
    cuisine: "Indian",
    mealTypes: ["breakfast", "lunch"],
    diets: VE,
    timeMin: 15,
    uses: ["rice", "onion", "peas", "carrot", "chili"],
    staples: ["mustard seeds", "turmeric"],
    ingredients: [
      "3 cups cooked rice",
      "onion and mixed veg",
      "mustard seeds and turmeric",
    ],
    steps: [
      "Pop mustard seeds in oil.",
      "Sauté onion and veg.",
      "Add rice and turmeric; toss until hot.",
    ],
    notes: "Uses scanned leftover rice early in a plan, as promised.",
    packable: false,
  },
  {
    id: "spring-rolls-fresh",
    name: "Fresh veg rolls",
    description: "Rice-paper or lettuce wraps with crunchy filling — no frying.",
    cuisine: "Thai",
    mealTypes: ["lunch", "snack", "lunchbox"],
    diets: VE,
    timeMin: 20,
    uses: ["lettuce", "carrot", "cucumber", "tofu", "pepper", "rice"],
    staples: ["rice paper or large lettuce leaves", "soy sauce"],
    ingredients: [
      "lettuce leaves or rice paper",
      "carrot, cucumber, optional tofu",
      "soy for dipping",
    ],
    steps: [
      "Cut filling into matchsticks.",
      "Roll tight in leaves or soaked rice paper.",
      "Pack dip separately.",
    ],
    notes: "Packing tip: wrap individually so they don't stick. Not smelly, not messy.",
    packable: true,
  },
  {
    id: "pho-ish",
    name: "Quick star-anise veg broth",
    description: "A Vietnamese-leaning noodle soup with whatever greens you have.",
    cuisine: "Chinese",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["onion", "ginger", "mushroom", "spinach", "tofu", "carrot"],
    staples: ["rice noodles", "soy sauce", "star anise or cinnamon"],
    ingredients: [
      "onion and ginger",
      "mushrooms",
      "rice noodles",
      "soy sauce",
      "tofu",
    ],
    steps: [
      "Simmer onion, ginger, and spice in water 15 minutes.",
      "Add mushrooms and tofu.",
      "Pour over soaked noodles.",
    ],
    notes: "No beef bones. Cinnamon stick if star anise is missing.",
    packable: false,
  },
  {
    id: "ratatouille",
    name: "One-pan summer veg stew",
    description: "Mediterranean vegetables collapsed into a spoonable stew.",
    cuisine: "Mediterranean",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["zucchini", "eggplant", "tomato", "pepper", "onion", "garlic"],
    staples: ["olive oil", "oregano"],
    ingredients: [
      "zucchini, eggplant, or both",
      "tomatoes and onion",
      "garlic and oregano",
    ],
    steps: [
      "Sauté onion and garlic.",
      "Add chunked veg and tomatoes.",
      "Simmer until silky, 25 minutes.",
    ],
    notes: "Eat with bread or rice. Better the next day.",
    packable: false,
  },
  {
    id: "breakfast-burrito",
    name: "Potato breakfast burrito",
    description: "Spiced potatoes, beans, and salsa in a wrap — scrambled tofu, not eggs.",
    cuisine: "Mexican",
    mealTypes: ["breakfast", "lunch"],
    diets: VE,
    timeMin: 25,
    uses: ["potato", "beans", "tortilla", "onion", "tomato", "tofu"],
    staples: ["tortillas", "cumin"],
    ingredients: [
      "2 potatoes, diced",
      "beans",
      "optional crumbled tofu",
      "tortillas",
    ],
    steps: [
      "Pan-fry potatoes with cumin until crisp.",
      "Warm beans and tofu.",
      "Wrap with tomato salsa.",
    ],
    notes: "Tofu scramble replaces eggs. Freeze extra wraps.",
    packable: true,
  },
  {
    id: "chicken-rice",
    name: "Lemon garlic chicken and rice",
    description: "One-pan chicken thighs with rice for non-veg nights under 40 minutes.",
    cuisine: "American",
    mealTypes: ["dinner"],
    diets: NV,
    timeMin: 40,
    uses: ["chicken", "rice", "lemon", "garlic", "onion"],
    staples: ["rice", "paprika"],
    ingredients: [
      "4 chicken thighs",
      "1 cup rice",
      "lemon and garlic",
      "onion",
    ],
    steps: [
      "Brown chicken; set aside.",
      "Sauté onion and garlic, add rice and water.",
      "Nestle chicken back, cover, cook 20 minutes.",
    ],
    notes: "Weeknight-timed. Use the lemon you already scanned.",
    packable: false,
  }
];
