import type { CatalogMeal, Diet } from "./types";

const V = ["vegetarian", "eggless_veg"] as Diet[];
const VE = ["vegetarian", "eggless_veg", "vegan"] as Diet[];
const NV = ["nonveg"] as Diet[];
const VG = ["vegetarian"] as Diet[];
const VN = ["vegetarian", "nonveg"] as Diet[];

export const CATALOG_02: CatalogMeal[] = [
  {
    id: "pad-thai-tofu",
    name: "Tamarind-less tofu pad Thai",
    description: "Rice noodles, tofu, and a lime-soy stand-in sauce when tamarind is missing.",
    cuisine: "Thai",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["tofu", "carrot", "onion", "lime", "lemon", "peanut", "cabbage"],
    staples: ["rice noodles", "soy sauce", "brown sugar"],
    ingredients: [
      "200 g rice noodles",
      "200 g tofu",
      "carrot and onion",
      "lime, soy, a pinch of sugar",
    ],
    steps: [
      "Soak noodles until flexible.",
      "Stir-fry tofu and veg.",
      "Add noodles, soy, sugar, and lime; toss fast.",
    ],
    notes: "No egg scramble. If rice noodles are out, use spaghetti and call it honest.",
    packable: false,
  },
  {
    id: "thai-curry",
    name: "Coconut veg curry",
    description: "A Thai-leaning coconut curry that flexes around whatever vegetables you scanned.",
    cuisine: "Thai",
    mealTypes: ["dinner"],
    diets: VE,
    timeMin: 35,
    uses: ["coconut milk", "pepper", "potato", "carrot", "spinach", "tofu", "broccoli"],
    staples: ["curry paste or curry powder", "coconut milk", "rice"],
    ingredients: [
      "1 can coconut milk",
      "3 cups mixed veg",
      "2 tbsp curry paste or powder",
      "tofu optional",
    ],
    steps: [
      "Fry paste in a little oil until fragrant.",
      "Add coconut milk and veg; simmer until tender.",
      "Season with salt and a squeeze of lime if you have it.",
    ],
    notes: "No fish sauce. Serve over rice. Mild enough for kids if you go easy on chili.",
    packable: false,
  },
  {
    id: "onigiri-box",
    name: "Seasoned rice onigiri box",
    description: "Salted rice balls with a veg filling — travels at room temp.",
    cuisine: "Japanese",
    mealTypes: ["lunch", "lunchbox"],
    diets: VE,
    timeMin: 20,
    uses: ["rice", "cucumber", "carrot", "avocado", "tofu"],
    staples: ["soy sauce", "nori or sesame seeds"],
    ingredients: [
      "2 cups cooked rice",
      "salt",
      "a filling: cucumber, leftover beans, or tofu",
      "soy for dipping",
    ],
    steps: [
      "Season warm rice with salt.",
      "Shape around a teaspoon of filling.",
      "Pack with cut veg on the side.",
    ],
    notes: "Packing tip: wrap each ball so they don't dry out. No fish flakes needed.",
    packable: true,
  },
  {
    id: "veg-katsu-bowl",
    name: "Crispy tofu rice bowl",
    description: "Pan-fried tofu over rice with a quick sweet-soy drizzle.",
    cuisine: "Japanese",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 25,
    uses: ["tofu", "rice", "cabbage", "carrot"],
    staples: ["soy sauce", "flour"],
    ingredients: [
      "300 g tofu",
      "cooked rice",
      "shredded cabbage",
      "soy and a pinch of sugar",
    ],
    steps: [
      "Press tofu, dust with flour, and pan-fry until gold.",
      "Stir soy and sugar for a drizzle.",
      "Serve over rice with cabbage.",
    ],
    notes: "No egg wash for the crust — flour only. Panko if you have it.",
    packable: false,
  },
  {
    id: "greek-bowl",
    name: "Lemon chickpea Greek bowl",
    description: "Chickpeas, cucumber, tomato, and yogurt-tahini if you keep it.",
    cuisine: "Mediterranean",
    mealTypes: ["lunch", "dinner", "lunchbox"],
    diets: V,
    timeMin: 15,
    uses: ["chickpeas", "cucumber", "tomato", "onion", "yogurt", "lemon", "olive"],
    staples: ["oregano", "olive oil"],
    ingredients: [
      "2 cups chickpeas",
      "cucumber, tomato, onion",
      "yogurt",
      "lemon and oregano",
    ],
    steps: [
      "Toss chickpeas with lemon, oil, and oregano.",
      "Chop the salad veg.",
      "Spoon yogurt on the side as a sauce.",
    ],
    notes: "Packing tip: keep yogurt in a separate cup. No feta required.",
    packable: true,
  },
  {
    id: "shakshuka-no",
    name: "Spiced tomato egg-free skillet",
    description: "Mediterranean peppers and tomatoes with chickpeas instead of eggs.",
    cuisine: "Mediterranean",
    mealTypes: ["breakfast", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["tomato", "pepper", "onion", "chickpeas", "spinach"],
    staples: ["paprika", "cumin"],
    ingredients: [
      "tomatoes and peppers",
      "1 onion",
      "1 can chickpeas",
      "paprika and cumin",
    ],
    steps: [
      "Cook onion and pepper until sweet.",
      "Add tomatoes and spices; simmer.",
      "Stir in chickpeas and heat through.",
    ],
    notes: "Bread for scooping. Fully eggless.",
    packable: false,
  },
  {
    id: "hummus-box",
    name: "Hummus and crunch box",
    description: "Homemade-fast hummus from canned chickpeas plus raw veg sticks.",
    cuisine: "Middle Eastern",
    mealTypes: ["lunch", "snack", "lunchbox"],
    diets: VE,
    timeMin: 10,
    uses: ["chickpeas", "lemon", "garlic", "carrot", "cucumber", "pepper"],
    staples: ["tahini or olive oil"],
    ingredients: [
      "1 can chickpeas",
      "1 garlic clove",
      "lemon juice",
      "carrot and cucumber sticks",
    ],
    steps: [
      "Mash or blend chickpeas with lemon, garlic, and oil or tahini.",
      "Cut veg into sticks.",
      "Pack hummus in a small pot with veg around it.",
    ],
    notes: "If tahini is missing, extra oil and a spoon of yogurt (not vegan) still works.",
    packable: true,
  },
  {
    id: "falafel-wrap",
    name: "Oven falafel wraps",
    description: "Chickpea patties baked, not fried, tucked into bread with salad.",
    cuisine: "Middle Eastern",
    mealTypes: ["lunch", "dinner", "lunchbox"],
    diets: VE,
    timeMin: 35,
    uses: ["chickpeas", "onion", "garlic", "parsley", "bread", "tomato", "cucumber"],
    staples: ["cumin", "flour"],
    ingredients: [
      "2 cups chickpeas",
      "onion and garlic",
      "cumin",
      "flour to bind (no egg)",
      "bread or pita",
    ],
    steps: [
      "Pulse chickpeas with onion, garlic, and cumin; bind with flour.",
      "Shape patties and bake or pan-fry.",
      "Wrap with tomato and cucumber.",
    ],
    notes: "Flour binds instead of egg. Packing tip: wrap tight in parchment.",
    packable: true,
  },
  {
    id: "bibimbap",
    name: "Veggie bibimbap",
    description: "Rice with seasoned vegetables and a gochujang drizzle — tofu instead of a fried egg.",
    cuisine: "Korean",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 35,
    uses: ["rice", "spinach", "carrot", "cucumber", "mushroom", "tofu"],
    staples: ["gochujang or chili paste", "sesame oil", "soy sauce"],
    ingredients: [
      "cooked rice",
      "3 kinds of veg, quickly sautéed",
      "tofu",
      "gochujang thinned with water",
    ],
    steps: [
      "Cook each veg quickly with a pinch of salt.",
      "Pan-fry tofu.",
      "Arrange over rice and drizzle sauce.",
    ],
    notes: "The usual fried egg is skipped. Sesame oil is worth asking about.",
    packable: false,
  },
  {
    id: "kimbap-veg",
    name: "Veggie kimbap rolls",
    description: "Rice rolls with carrot, cucumber, and pickled bits — school-lunch gold.",
    cuisine: "Korean",
    mealTypes: ["lunch", "lunchbox"],
    diets: VE,
    timeMin: 30,
    uses: ["rice", "carrot", "cucumber", "spinach", "tofu"],
    staples: ["nori sheets", "sesame oil"],
    ingredients: [
      "2 cups seasoned rice",
      "carrot and cucumber sticks",
      "spinach or tofu strips",
      "nori",
    ],
    steps: [
      "Season rice with a drop of sesame oil and salt.",
      "Lay fillings on nori and rice; roll tight.",
      "Slice with a wet knife after a 5-minute rest.",
    ],
    notes: "Packing tip: slice at home so little hands can eat without mess. No fish cake, no egg strip.",
    packable: true,
  }
];
