import type { CatalogMeal, Diet } from "./types";

const V = ["vegetarian", "eggless_veg"] as Diet[];
const VE = ["vegetarian", "eggless_veg", "vegan"] as Diet[];
const NV = ["nonveg"] as Diet[];
const VG = ["vegetarian"] as Diet[];
const VN = ["vegetarian", "nonveg"] as Diet[];

export const CATALOG_07: CatalogMeal[] = [
  {
    id: "mujaddara-bowl",
    name: "Herbed lentil rice bowl",
    description: "A faster cousin of mujaddara with lemon and leftover greens.",
    cuisine: "Middle Eastern",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["lentils", "rice", "onion", "spinach", "lemon"],
    staples: ["cumin"],
    ingredients: ["lentils", "rice", "onion", "cumin", "lemon"],
    steps: ["Cook lentils and rice (together if you're brave).", "Fry onions.", "Pile with lemon."],
    notes: "Repeats well across a week without wasting spices.",
    packable: false,
  },
  {
    id: "fattoush-box",
    name: "Broken-bread fattoush",
    description: "Tomato-cucumber salad with toasted leftover bread.",
    cuisine: "Middle Eastern",
    mealTypes: ["lunch", "lunchbox"],
    diets: VE,
    timeMin: 15,
    uses: ["tomato", "cucumber", "onion", "bread", "lemon", "lettuce"],
    staples: ["sumac or lemon zest", "olive oil"],
    ingredients: ["tomato and cucumber", "stale bread", "lemon", "onion"],
    steps: ["Toast bread pieces.", "Chop salad.", "Toss with lemon just before eating."],
    notes: "Packing tip: keep bread dry until lunch.",
    packable: true,
  },
  {
    id: "doenjang-stew",
    name: "Soft tofu stew",
    description: "A Korean-leaning soybean stew with whatever veg is tired.",
    cuisine: "Korean",
    mealTypes: ["dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["tofu", "zucchini", "onion", "mushroom", "spinach"],
    staples: ["doenjang or miso", "gochugaru or chili flakes"],
    ingredients: ["tofu", "onion and mushroom", "miso or doenjang", "chili flakes"],
    steps: ["Simmer onion and mushroom.", "Whisk in miso off a rolling boil.", "Add tofu gently."],
    notes: "Miso is the pantry stand-in for doenjang.",
    packable: false,
  },
  {
    id: "scallion-pancake",
    name: "Crispy scallion pancakes",
    description: "Flour, water, scallion or onion — no egg in the dough.",
    cuisine: "Chinese",
    mealTypes: ["snack", "breakfast", "dinner"],
    diets: VE,
    timeMin: 25,
    uses: ["scallion", "onion", "flour"],
    staples: ["flour", "sesame oil"],
    ingredients: ["flour", "hot water", "scallion or onion", "salt"],
    steps: ["Make a soft dough.", "Roll with chopped scallion.", "Pan-fry until blistered."],
    notes: "Dipping soy on the side. Fully eggless.",
    packable: false,
  },
  {
    id: "sloppy-lentil",
    name: "Sloppy lentil toast",
    description: "American diner energy, vegetarian, piled on bread.",
    cuisine: "American",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["lentils", "onion", "tomato", "pepper", "bread"],
    staples: ["ketchup or tomato paste", "chili powder"],
    ingredients: ["lentils", "onion and pepper", "tomato", "bread"],
    steps: ["Sauté onion and pepper.", "Add lentils, tomato, chili.", "Spoon onto toast."],
    notes: "No mystery meat. Kids usually approve.",
    packable: false,
  },
  {
    id: "loaded-potato",
    name: "Loaded skillet potatoes",
    description: "Crisp potatoes with yogurt, cheese, and whatever veg is left.",
    cuisine: "American",
    mealTypes: ["breakfast", "dinner"],
    diets: V,
    timeMin: 30,
    uses: ["potato", "yogurt", "cheese", "onion", "spinach", "pepper"],
    staples: ["paprika"],
    ingredients: ["potatoes", "onion", "yogurt or cheese", "paprika"],
    steps: ["Pan-fry potatoes until crisp.", "Add onion and greens.", "Finish with yogurt or cheese."],
    notes: "No sour cream required. Vegan: skip dairy, add lemon.",
    packable: false,
  },
  {
    id: "chicken-wrap",
    name: "Lemon chicken lunch wrap",
    description: "Cold leftover chicken, cucumber, and bread — packs without reheating.",
    cuisine: "American",
    mealTypes: ["lunch", "lunchbox"],
    diets: NV,
    timeMin: 15,
    uses: ["chicken", "cucumber", "bread", "tortilla", "yogurt", "lettuce"],
    staples: ["wraps or bread"],
    ingredients: ["cooked chicken", "cucumber", "bread or wrap", "yogurt smear"],
    steps: ["Slice leftover chicken.", "Spread yogurt, add cucumber.", "Wrap tight and pack."],
    notes: "Packing tip: wrap in parchment so it doesn't go soggy. Cool chicken first.",
    packable: true,
  },
  {
    id: "tuna-box",
    name: "Tuna cucumber sandwich box",
    description: "Tuna mashed with yogurt (not mayo), cucumber, bread. Fine at room temp for hours.",
    cuisine: "American",
    mealTypes: ["lunch", "lunchbox"],
    diets: NV,
    timeMin: 10,
    uses: ["tuna", "cucumber", "bread", "yogurt", "lemon"],
    staples: ["canned tuna"],
    ingredients: ["canned tuna", "yogurt", "cucumber", "bread", "lemon"],
    steps: ["Mash tuna with yogurt and lemon.", "Layer with cucumber on bread.", "Pack veg sticks on the side."],
    notes: "Yogurt instead of mayo. Packing tip: keep filling and bread apart if the morning is humid.",
    packable: true,
  }
];
