import type { CatalogMeal, Diet } from "./types";

const V = ["vegetarian", "eggless_veg"] as Diet[];
const VE = ["vegetarian", "eggless_veg", "vegan"] as Diet[];
const NV = ["nonveg"] as Diet[];
const VG = ["vegetarian"] as Diet[];
const VN = ["vegetarian", "nonveg"] as Diet[];

export const CATALOG_00: CatalogMeal[] = [
  {
    id: "oat-yogurt",
    name: "Lemon yogurt oats",
    description: "Warm oats with yogurt, a squeeze of lemon, and whatever fruit you have.",
    cuisine: "American",
    mealTypes: ["breakfast"],
    diets: V,
    timeMin: 10,
    uses: ["oats", "yogurt", "lemon", "milk", "banana", "honey"],
    staples: ["rolled oats", "honey"],
    ingredients: [
      "1 cup rolled oats",
      "1 cup milk or water",
      "1/2 cup yogurt",
      "1/2 lemon, juiced",
      "fruit you have, sliced",
    ],
    steps: [
      "Simmer oats in milk until creamy, about 5 minutes.",
      "Stir in yogurt off the heat so it stays silky.",
      "Finish with lemon and fruit.",
    ],
    notes: "Skip honey for a fully unsweetened bowl. Maple works if you keep it.",
    packable: false,
  },
  {
    id: "masala-oats",
    name: "Masala vegetable oats",
    description: "Savory Indian breakfast oats with onion, tomato, and a pinch of turmeric.",
    cuisine: "Indian",
    mealTypes: ["breakfast", "snack"],
    diets: VE,
    timeMin: 15,
    uses: ["oats", "onion", "tomato", "carrot", "peas", "spinach"],
    staples: ["rolled oats", "turmeric", "cumin"],
    ingredients: [
      "1 cup rolled oats",
      "1/2 onion, chopped",
      "1 tomato, chopped",
      "handful mixed veg",
      "1/2 tsp cumin and turmeric",
    ],
    steps: [
      "Sauté onion in a little oil until soft.",
      "Add tomato, spices, and veg; cook 2 minutes.",
      "Stir in oats and 2 cups water; simmer until thick.",
    ],
    notes: "Eggless and filling. Leftovers reheat with a splash of water.",
    packable: false,
  },
  {
    id: "avocado-toast",
    name: "Chili lemon avocado toast",
    description: "Mashed avocado on toasted bread with lemon, chili, and a crunchy topping.",
    cuisine: "American",
    mealTypes: ["breakfast", "lunch", "snack"],
    diets: VE,
    timeMin: 8,
    uses: ["avocado", "bread", "lemon", "tomato", "chili"],
    staples: ["chili flakes"],
    ingredients: [
      "2 slices bread",
      "1 avocado",
      "1/2 lemon",
      "pinch chili flakes",
      "salt",
    ],
    steps: [
      "Toast the bread.",
      "Mash avocado with lemon and salt.",
      "Spread thick and finish with chili.",
    ],
    notes: "No egg wash, no mayo. Tomato slices if you have them.",
    packable: false,
  },
  {
    id: "besan-chilla",
    name: "Besan chilla",
    description: "Savory chickpea-flour pancakes packed with onion and greens — no eggs.",
    cuisine: "Indian",
    mealTypes: ["breakfast", "lunch", "snack", "lunchbox"],
    diets: VE,
    timeMin: 20,
    uses: ["onion", "spinach", "tomato", "chili", "carrot"],
    staples: ["chickpea flour (besan)", "turmeric"],
    ingredients: [
      "1 cup chickpea flour",
      "1/2 onion, fine chop",
      "handful spinach, chopped",
      "1/2 tsp turmeric",
      "water to make a pourable batter",
    ],
    steps: [
      "Whisk flour, turmeric, salt, and water until smooth.",
      "Fold in onion and spinach.",
      "Pour thin pancakes in a hot pan and cook both sides.",
    ],
    notes: "This is the eggless stand-in for an omelette. Packs well at room temp.",
    packable: true,
  },
  {
    id: "shakshuka-tofu",
    name: "Tofu shakshuka",
    description: "Tomato-pepper skillet with cubed tofu instead of eggs.",
    cuisine: "Middle Eastern",
    mealTypes: ["breakfast", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["tomato", "pepper", "onion", "tofu", "garlic", "spinach"],
    staples: ["cumin", "paprika"],
    ingredients: [
      "4 tomatoes or 1 can crushed tomatoes",
      "1 onion and 1 bell pepper",
      "200 g tofu, cubed",
      "2 garlic cloves",
      "1 tsp cumin and paprika",
    ],
    steps: [
      "Sauté onion, pepper, and garlic.",
      "Add tomatoes and spices; simmer 10 minutes.",
      "Nestle tofu in the sauce and simmer until hot.",
    ],
    notes: "Classic shakshuka uses eggs; we use tofu so it stays eggless. Serve with bread.",
    packable: false,
  },
  {
    id: "miso-soup",
    name: "Weeknight miso bowl",
    description: "A fast Japanese soup with tofu, greens, and whatever veg is wilting.",
    cuisine: "Japanese",
    mealTypes: ["lunch", "dinner", "snack"],
    diets: VE,
    timeMin: 15,
    uses: ["tofu", "spinach", "mushroom", "scallion", "carrot"],
    staples: ["miso paste", "soy sauce"],
    ingredients: [
      "2 tbsp miso paste",
      "150 g tofu",
      "handful greens or mushrooms",
      "2 cups water",
      "splash soy sauce",
    ],
    steps: [
      "Simmer veg in water until just tender.",
      "Turn off heat and whisk in miso so it stays fragrant.",
      "Add tofu and soy; serve immediately.",
    ],
    notes: "Never boil miso hard. Add cooked rice to make it a meal.",
    packable: false,
  },
  {
    id: "veg-fried-rice",
    name: "Kitchen-sink fried rice",
    description: "Day-old rice, a hot pan, and every leftover vegetable — no egg scramble.",
    cuisine: "Chinese",
    mealTypes: ["lunch", "dinner", "lunchbox"],
    diets: VE,
    timeMin: 20,
    uses: ["rice", "carrot", "peas", "onion", "garlic", "cabbage", "tofu"],
    staples: ["soy sauce", "sesame oil"],
    ingredients: [
      "3 cups cooked rice",
      "2 cups mixed veg",
      "2 garlic cloves",
      "2 tbsp soy sauce",
      "optional cubed tofu",
    ],
    steps: [
      "Stir-fry garlic and veg on high heat.",
      "Add rice, breaking clumps, and toss until hot.",
      "Season with soy and a drop of sesame oil.",
    ],
    notes: "Skip the usual egg. Cold rice fries better than fresh. Lunchbox-friendly once cool.",
    packable: true,
  },
  {
    id: "chana-masala",
    name: "Tomato chana masala",
    description: "Chickpeas in a thick onion-tomato gravy — pantry dinner that feels like a plan.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 35,
    uses: ["chickpeas", "onion", "tomato", "garlic", "ginger", "spinach"],
    staples: ["garam masala", "cumin", "turmeric"],
    ingredients: [
      "2 cups cooked chickpeas",
      "1 onion, 2 tomatoes",
      "garlic and ginger",
      "1 tsp garam masala, cumin, turmeric",
    ],
    steps: [
      "Brown onion, then garlic and ginger.",
      "Add tomatoes and spices; cook until jammy.",
      "Stir in chickpeas with a splash of water and simmer 10 minutes.",
    ],
    notes: "Serve with rice or bread. Freezes well. No cream, no egg.",
    packable: false,
  },
  {
    id: "dal-tadka",
    name: "Everyday dal tadka",
    description: "Lentils simmered until creamy, finished with cumin and garlic.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["lentils", "dal", "onion", "tomato", "garlic", "spinach"],
    staples: ["red lentils or toor dal", "cumin", "turmeric"],
    ingredients: [
      "1 cup lentils",
      "1 onion, 1 tomato",
      "3 garlic cloves",
      "1 tsp cumin and turmeric",
    ],
    steps: [
      "Simmer lentils with turmeric until soft.",
      "Sauté onion, garlic, and tomato; add to dal.",
      "Bloom cumin in a little oil and pour over the top.",
    ],
    notes: "If you only have canned lentils, shorten the simmer. Rice on the side.",
    packable: false,
  },
  {
    id: "palak-paneer",
    name: "Weeknight palak paneer",
    description: "Spinach gravy with cubes of paneer — dairy-friendly, fully eggless.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: V,
    timeMin: 35,
    uses: ["spinach", "paneer", "onion", "tomato", "garlic", "ginger"],
    staples: ["garam masala", "cumin"],
    ingredients: [
      "a big bunch of spinach",
      "200 g paneer",
      "1 onion, 1 tomato",
      "garlic, ginger, garam masala",
    ],
    steps: [
      "Wilt spinach, then blend with a splash of water.",
      "Sauté onion, tomato, and spices.",
      "Add spinach puree and paneer; simmer 5 minutes.",
    ],
    notes: "No cream required. Tofu stands in for a vegan version.",
    packable: false,
  }
];
