import type { CatalogMeal, Diet } from "./types";

const V = ["vegetarian", "eggless_veg"] as Diet[];
const VE = ["vegetarian", "eggless_veg", "vegan"] as Diet[];
const NV = ["nonveg"] as Diet[];
const VG = ["vegetarian"] as Diet[];
const VN = ["vegetarian", "nonveg"] as Diet[];

export const CATALOG_05: CatalogMeal[] = [
  {
    id: "rajma",
    name: "Tomato rajma",
    description: "Kidney beans in a slow onion-tomato gravy. Rice on the side.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["beans", "kidney beans", "rajma", "onion", "tomato", "garlic"],
    staples: ["rajma or canned kidney beans", "garam masala"],
    ingredients: ["2 cups kidney beans", "onion and tomato", "garlic", "garam masala"],
    steps: ["Sauté onion and garlic.", "Add tomato and spices.", "Simmer beans 15 minutes."],
    notes: "Canned beans keep it weeknight. Fully eggless.",
    packable: false,
  },
  {
    id: "veg-korma",
    name: "Mild coconut korma",
    description: "Soft vegetables in a gentle coconut gravy — kid-friendly spice.",
    cuisine: "Indian",
    mealTypes: ["dinner"],
    diets: VE,
    timeMin: 35,
    uses: ["potato", "carrot", "peas", "onion", "spinach", "paneer"],
    staples: ["coconut milk", "garam masala"],
    ingredients: ["mixed veg", "onion", "coconut milk", "garam masala"],
    steps: ["Sauté onion.", "Add veg and coconut milk.", "Simmer until the potato yields."],
    notes: "No cream, no nut paste required if coconut milk is there.",
    packable: false,
  },
  {
    id: "mushroom-masala",
    name: "Bhuna mushroom masala",
    description: "Mushrooms cooked down with onion, tomato, and garam masala.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 25,
    uses: ["mushroom", "onion", "tomato", "garlic", "peas"],
    staples: ["garam masala", "cumin"],
    ingredients: ["mushrooms", "onion and tomato", "garlic", "garam masala"],
    steps: ["Sear mushrooms until they give up water.", "Add onion, tomato, spices.", "Cook until thick."],
    notes: "Works as a wrap filling the next day.",
    packable: false,
  },
  {
    id: "baingan",
    name: "Smoky baingan mash",
    description: "Roasted eggplant mashed with onion, tomato, and lemon.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 35,
    uses: ["eggplant", "onion", "tomato", "garlic", "lemon"],
    staples: ["cumin"],
    ingredients: ["1 large eggplant", "onion and tomato", "garlic", "lemon"],
    steps: ["Roast or pan-char eggplant until collapsed.", "Mash with sautéed onion and tomato.", "Finish with lemon."],
    notes: "Bread or rice. No yogurt required.",
    packable: false,
  },
  {
    id: "sambar-veg",
    name: "Weeknight sambar",
    description: "Lentil-tamarind stew with whatever vegetables are on the way out.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["lentils", "dal", "onion", "tomato", "carrot", "spinach"],
    staples: ["sambar powder or cumin+coriander", "tamarind or lemon"],
    ingredients: ["lentils", "mixed veg", "tomato", "sambar powder or lemon"],
    steps: ["Cook lentils until soft.", "Add veg and spice.", "Sour with lemon if tamarind is missing."],
    notes: "Lemon stands in for tamarind. Eggless, of course.",
    packable: false,
  },
  {
    id: "poha",
    name: "Kanda poha",
    description: "Flattened rice with onion, mustard seed, and lemon — breakfast or light dinner.",
    cuisine: "Indian",
    mealTypes: ["breakfast", "snack", "dinner"],
    diets: VE,
    timeMin: 15,
    uses: ["onion", "potato", "peas", "lemon", "chili"],
    staples: ["poha (flattened rice)", "mustard seeds", "turmeric"],
    ingredients: ["2 cups poha", "onion", "optional potato", "lemon", "turmeric"],
    steps: ["Rinse poha and drain.", "Pop mustard seeds; sauté onion.", "Toss poha with turmeric and lemon."],
    notes: "If poha is missing, leftover rice upma is the honest swap.",
    packable: false,
  },
  {
    id: "pav-style-mash",
    name: "Pav-style potato masala",
    description: "Street-style spiced potatoes piled on bread or eaten with a spoon.",
    cuisine: "Indian",
    mealTypes: ["breakfast", "lunch", "dinner", "snack"],
    diets: VE,
    timeMin: 25,
    uses: ["potato", "onion", "bread", "peas", "lemon"],
    staples: ["mustard seeds", "turmeric"],
    ingredients: ["potatoes", "onion", "bread", "turmeric", "lemon"],
    steps: ["Boil and roughly mash potatoes.", "Sauté onion and spices.", "Fold together and pile on toast."],
    notes: "No pav? Any bread. No egg wash on the bun.",
    packable: true,
  },
  {
    id: "aglio-spinaci",
    name: "Spinach aglio e olio",
    description: "Garlic oil pasta with a heap of greens from the fridge.",
    cuisine: "Italian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 20,
    uses: ["spinach", "garlic", "chili", "lemon"],
    staples: ["egg-free pasta", "olive oil", "chili flakes"],
    ingredients: ["pasta", "lots of spinach", "garlic", "chili flakes", "lemon"],
    steps: ["Boil egg-free pasta.", "Sizzle garlic and chili in oil.", "Wilt spinach and toss pasta in."],
    notes: "Confirm egg-free pasta. Lemon instead of cheese for vegan.",
    packable: false,
  },
  {
    id: "white-bean-stew",
    name: "Rosemary white bean stew",
    description: "A Tuscan-leaning pot of beans, tomato, and greens.",
    cuisine: "Italian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["beans", "tomato", "spinach", "onion", "garlic", "carrot"],
    staples: ["dried rosemary or oregano"],
    ingredients: ["beans", "tomato", "greens", "onion", "garlic"],
    steps: ["Sauté onion, carrot, garlic.", "Add tomato and beans.", "Simmer and fold in greens."],
    notes: "Bread for dipping. No parmesan required.",
    packable: false,
  },
  {
    id: "elote-bowl",
    name: "Chili-lime corn bowl",
    description: "Warm corn, chili, lime, and whatever cheese you have — no mayo.",
    cuisine: "Mexican",
    mealTypes: ["lunch", "snack", "dinner"],
    diets: V,
    timeMin: 15,
    uses: ["corn", "lime", "lemon", "chili", "cheese", "onion"],
    staples: ["chili powder"],
    ingredients: ["corn", "lime", "chili powder", "optional cheese"],
    steps: ["Warm corn in a pan.", "Toss with lime and chili.", "Crumble cheese on top if dairy is welcome."],
    notes: "Yogurt instead of mayo. Vegan: skip cheese.",
    packable: true,
  }
];
