import type { CatalogMeal, Diet } from "./types";

const V = ["vegetarian", "eggless_veg"] as Diet[];
const VE = ["vegetarian", "eggless_veg", "vegan"] as Diet[];
const NV = ["nonveg"] as Diet[];
const VG = ["vegetarian"] as Diet[];
const VN = ["vegetarian", "nonveg"] as Diet[];

export const CATALOG_01: CatalogMeal[] = [
  {
    id: "aloo-paratha-style",
    name: "Skillet aloo mash wraps",
    description: "Spiced potato filling tucked into whatever flatbread you have.",
    cuisine: "Indian",
    mealTypes: ["breakfast", "lunch", "lunchbox"],
    diets: VE,
    timeMin: 25,
    uses: ["potato", "onion", "bread", "tortilla", "chili", "peas"],
    staples: ["cumin", "garam masala"],
    ingredients: [
      "3 potatoes, boiled and mashed",
      "1/2 onion, chopped",
      "cumin and garam masala",
      "4 tortillas or leftover roti",
    ],
    steps: [
      "Mix mash with onion and spices.",
      "Spread on bread and fold.",
      "Toast in a dry pan until both sides spot.",
    ],
    notes: "Packs well for school. Cool before wrapping so it doesn't steam soggy.",
    packable: true,
  },
  {
    id: "pasta-pomodoro",
    name: "Tomato garlic pasta",
    description: "A 20-minute Italian bowl: tomatoes, garlic, pasta, and a little cheese if you have it.",
    cuisine: "Italian",
    mealTypes: ["lunch", "dinner"],
    diets: V,
    timeMin: 25,
    uses: ["tomato", "garlic", "onion", "basil", "cheese", "spinach"],
    staples: ["dried pasta", "olive oil", "chili flakes"],
    ingredients: [
      "250 g dried pasta (egg-free)",
      "4 tomatoes or 1 can",
      "3 garlic cloves",
      "olive oil and chili flakes",
      "optional grated cheese",
    ],
    steps: [
      "Boil egg-free pasta in salted water.",
      "Sizzle garlic in oil, add tomatoes, and simmer.",
      "Toss pasta in the sauce with a splash of cooking water.",
    ],
    notes: "Use egg-free pasta, not egg noodles. If pasta is missing, use rice or zucchini ribbons.",
    packable: false,
  },
  {
    id: "minestrone",
    name: "Fridge minestrone",
    description: "A vegetable soup that uses odds and ends, finished with beans and pasta or rice.",
    cuisine: "Italian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["carrot", "onion", "celery", "tomato", "beans", "spinach", "zucchini"],
    staples: ["dried pasta or rice", "oregano"],
    ingredients: [
      "onion, carrot, and whatever veg",
      "1 can tomatoes",
      "1 can beans",
      "handful pasta or leftover rice",
      "oregano",
    ],
    steps: [
      "Sauté onion and carrot.",
      "Add tomatoes, water, beans, and veg; simmer 20 minutes.",
      "Stir in pasta until tender.",
    ],
    notes: "Choose short egg-free pasta. Excellent next-day lunch.",
    packable: false,
  },
  {
    id: "caprese-box",
    name: "Caprese lunchbox",
    description: "Tomatoes, cheese, and bread packed as a not-soggy school or work box.",
    cuisine: "Italian",
    mealTypes: ["lunch", "lunchbox"],
    diets: V,
    timeMin: 10,
    uses: ["tomato", "cheese", "mozzarella", "bread", "basil"],
    staples: ["olive oil"],
    ingredients: [
      "2 tomatoes",
      "cheese you have, cubed",
      "bread or crackers",
      "olive oil pinch of salt",
    ],
    steps: [
      "Cube tomato and cheese; keep bread separate.",
      "Pack oil in a tiny container if you can.",
      "Assemble just before eating so bread stays crisp.",
    ],
    notes: "Packing tip: wrap bread in a dry napkin. No mayo, no egg.",
    packable: true,
  },
  {
    id: "bean-tacos",
    name: "Smoky bean tacos",
    description: "Cumin-scented beans, salsa-ish tomatoes, and tortillas — weeknight Mexican.",
    cuisine: "Mexican",
    mealTypes: ["lunch", "dinner", "lunchbox"],
    diets: VE,
    timeMin: 25,
    uses: ["beans", "chickpeas", "tomato", "onion", "avocado", "lettuce", "cheese"],
    staples: ["tortillas", "cumin", "chili powder"],
    ingredients: [
      "2 cups beans",
      "1 onion, 2 tomatoes",
      "1 tsp cumin",
      "8 tortillas",
      "optional avocado",
    ],
    steps: [
      "Sauté onion, add beans, cumin, and a splash of water; mash slightly.",
      "Warm tortillas.",
      "Fill with beans, tomato, and whatever crunchy bits you have.",
    ],
    notes: "Lunchbox: pack fillings and tortillas apart. No sour-cream-only richness required.",
    packable: true,
  },
  {
    id: "quesadilla",
    name: "Veggie cheese quesadilla",
    description: "Crisp tortilla, melted cheese, and leftover vegetables. Ten minutes, one pan.",
    cuisine: "Mexican",
    mealTypes: ["lunch", "snack", "lunchbox"],
    diets: V,
    timeMin: 10,
    uses: ["tortilla", "cheese", "spinach", "pepper", "onion", "beans"],
    staples: ["tortillas"],
    ingredients: [
      "4 tortillas",
      "1 cup grated cheese",
      "handful leftover veg",
    ],
    steps: [
      "Scatter cheese and veg on a tortilla.",
      "Top with a second tortilla and toast both sides.",
      "Rest one minute, then slice.",
    ],
    notes: "Cool before packing so cheese sets. No egg wash on the edges.",
    packable: true,
  },
  {
    id: "veg-chili",
    name: "One-pot veg chili",
    description: "Beans, tomatoes, and chili warmth. Makes leftovers on purpose.",
    cuisine: "American",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["beans", "tomato", "onion", "pepper", "corn", "carrot"],
    staples: ["chili powder", "cumin"],
    ingredients: [
      "2 cans beans",
      "1 can tomatoes",
      "onion and pepper",
      "chili powder and cumin",
    ],
    steps: [
      "Sauté onion and pepper.",
      "Add tomatoes, beans, spices, and a cup of water.",
      "Simmer 20 minutes until thick.",
    ],
    notes: "Repeats well across a week. Eat with rice or bread.",
    packable: false,
  },
  {
    id: "grilled-cheese",
    name: "Tomato grilled cheese",
    description: "The American classic with sliced tomato inside, pan-toasted in a little oil.",
    cuisine: "American",
    mealTypes: ["lunch", "snack"],
    diets: V,
    timeMin: 12,
    uses: ["bread", "cheese", "tomato"],
    staples: [],
    ingredients: [
      "4 slices bread",
      "cheese slices or grated cheese",
      "tomato slices",
    ],
    steps: [
      "Layer cheese and tomato between bread.",
      "Toast in a lightly oiled pan until gold.",
      "Rest 1 minute so the cheese settles.",
    ],
    notes: "Butter is nice; oil works. No egg wash.",
    packable: false,
  },
  {
    id: "veg-stirfry",
    name: "Garlic veg stir-fry",
    description: "High-heat vegetables with soy. Serve over rice or noodles.",
    cuisine: "Chinese",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 20,
    uses: ["broccoli", "pepper", "carrot", "cabbage", "garlic", "tofu", "mushroom"],
    staples: ["soy sauce", "cornstarch"],
    ingredients: [
      "4 cups chopped veg",
      "optional tofu",
      "3 garlic cloves",
      "2 tbsp soy sauce",
    ],
    steps: [
      "Sear tofu if using; set aside.",
      "Stir-fry veg and garlic on high heat.",
      "Add soy and a splash of water; toss tofu back in.",
    ],
    notes: "If you don't have cornstarch, skip the glaze — it still tastes good.",
    packable: false,
  },
  {
    id: "mapo-tofu-veg",
    name: "Gentle mapo-style tofu",
    description: "Soft tofu in a chili-bean sauce without minced meat.",
    cuisine: "Chinese",
    mealTypes: ["dinner"],
    diets: VE,
    timeMin: 25,
    uses: ["tofu", "garlic", "ginger", "scallion", "mushroom"],
    staples: ["soy sauce", "chili bean paste or chili flakes"],
    ingredients: [
      "400 g tofu",
      "garlic and ginger",
      "soy sauce and chili paste",
      "mushrooms if you have them",
    ],
    steps: [
      "Sauté garlic, ginger, and mushrooms.",
      "Add soy, chili, and a little water.",
      "Slide in tofu and simmer gently.",
    ],
    notes: "Traditionally pork; mushrooms keep it vegetarian. Rice is essential.",
    packable: false,
  }
];
