import type { CatalogMeal, Diet } from "./types";

const V = ["vegetarian", "eggless_veg"] as Diet[];
const VE = ["vegetarian", "eggless_veg", "vegan"] as Diet[];
const NV = ["nonveg"] as Diet[];
const VG = ["vegetarian"] as Diet[];
const VN = ["vegetarian", "nonveg"] as Diet[];

export const CATALOG_A: CatalogMeal[] = [
  {
    id: "oat-yogurt",
    name: "Lemon yogurt oats",
    description: "Warm oats with yogurt, a squeeze of lemon, and whatever fruit you have.",
    cuisine: "American",
    mealTypes: ["breakfast"],
    diets: V,
    timeMin: 10,
    uses: ["oats", "yogurt", "lemon", "milk", "banana", "honey"],
    staples: ["rolled oats", "honey"],
    ingredients: [
      "1 cup rolled oats",
      "1 cup milk or water",
      "1/2 cup yogurt",
      "1/2 lemon, juiced",
      "fruit you have, sliced",
    ],
    steps: [
      "Simmer oats in milk until creamy, about 5 minutes.",
      "Stir in yogurt off the heat so it stays silky.",
      "Finish with lemon and fruit.",
    ],
    notes: "Skip honey for a fully unsweetened bowl. Maple works if you keep it.",
    packable: false,
  },
  {
    id: "masala-oats",
    name: "Masala vegetable oats",
    description: "Savory Indian breakfast oats with onion, tomato, and a pinch of turmeric.",
    cuisine: "Indian",
    mealTypes: ["breakfast", "snack"],
    diets: VE,
    timeMin: 15,
    uses: ["oats", "onion", "tomato", "carrot", "peas", "spinach"],
    staples: ["rolled oats", "turmeric", "cumin"],
    ingredients: [
      "1 cup rolled oats",
      "1/2 onion, chopped",
      "1 tomato, chopped",
      "handful mixed veg",
      "1/2 tsp cumin and turmeric",
    ],
    steps: [
      "Sauté onion in a little oil until soft.",
      "Add tomato, spices, and veg; cook 2 minutes.",
      "Stir in oats and 2 cups water; simmer until thick.",
    ],
    notes: "Eggless and filling. Leftovers reheat with a splash of water.",
    packable: false,
  },
  {
    id: "avocado-toast",
    name: "Chili lemon avocado toast",
    description: "Mashed avocado on toasted bread with lemon, chili, and a crunchy topping.",
    cuisine: "American",
    mealTypes: ["breakfast", "lunch", "snack"],
    diets: VE,
    timeMin: 8,
    uses: ["avocado", "bread", "lemon", "tomato", "chili"],
    staples: ["chili flakes"],
    ingredients: [
      "2 slices bread",
      "1 avocado",
      "1/2 lemon",
      "pinch chili flakes",
      "salt",
    ],
    steps: [
      "Toast the bread.",
      "Mash avocado with lemon and salt.",
      "Spread thick and finish with chili.",
    ],
    notes: "No egg wash, no mayo. Tomato slices if you have them.",
    packable: false,
  },
  {
    id: "besan-chilla",
    name: "Besan chilla",
    description: "Savory chickpea-flour pancakes packed with onion and greens — no eggs.",
    cuisine: "Indian",
    mealTypes: ["breakfast", "lunch", "snack", "lunchbox"],
    diets: VE,
    timeMin: 20,
    uses: ["onion", "spinach", "tomato", "chili", "carrot"],
    staples: ["chickpea flour (besan)", "turmeric"],
    ingredients: [
      "1 cup chickpea flour",
      "1/2 onion, fine chop",
      "handful spinach, chopped",
      "1/2 tsp turmeric",
      "water to make a pourable batter",
    ],
    steps: [
      "Whisk flour, turmeric, salt, and water until smooth.",
      "Fold in onion and spinach.",
      "Pour thin pancakes in a hot pan and cook both sides.",
    ],
    notes: "This is the eggless stand-in for an omelette. Packs well at room temp.",
    packable: true,
  },
  {
    id: "shakshuka-tofu",
    name: "Tofu shakshuka",
    description: "Tomato-pepper skillet with cubed tofu instead of eggs.",
    cuisine: "Middle Eastern",
    mealTypes: ["breakfast", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["tomato", "pepper", "onion", "tofu", "garlic", "spinach"],
    staples: ["cumin", "paprika"],
    ingredients: [
      "4 tomatoes or 1 can crushed tomatoes",
      "1 onion and 1 bell pepper",
      "200 g tofu, cubed",
      "2 garlic cloves",
      "1 tsp cumin and paprika",
    ],
    steps: [
      "Sauté onion, pepper, and garlic.",
      "Add tomatoes and spices; simmer 10 minutes.",
      "Nestle tofu in the sauce and simmer until hot.",
    ],
    notes: "Classic shakshuka uses eggs; we use tofu so it stays eggless. Serve with bread.",
    packable: false,
  },
  {
    id: "miso-soup",
    name: "Weeknight miso bowl",
    description: "A fast Japanese soup with tofu, greens, and whatever veg is wilting.",
    cuisine: "Japanese",
    mealTypes: ["lunch", "dinner", "snack"],
    diets: VE,
    timeMin: 15,
    uses: ["tofu", "spinach", "mushroom", "scallion", "carrot"],
    staples: ["miso paste", "soy sauce"],
    ingredients: [
      "2 tbsp miso paste",
      "150 g tofu",
      "handful greens or mushrooms",
      "2 cups water",
      "splash soy sauce",
    ],
    steps: [
      "Simmer veg in water until just tender.",
      "Turn off heat and whisk in miso so it stays fragrant.",
      "Add tofu and soy; serve immediately.",
    ],
    notes: "Never boil miso hard. Add cooked rice to make it a meal.",
    packable: false,
  },
  {
    id: "veg-fried-rice",
    name: "Kitchen-sink fried rice",
    description: "Day-old rice, a hot pan, and every leftover vegetable — no egg scramble.",
    cuisine: "Chinese",
    mealTypes: ["lunch", "dinner", "lunchbox"],
    diets: VE,
    timeMin: 20,
    uses: ["rice", "carrot", "peas", "onion", "garlic", "cabbage", "tofu"],
    staples: ["soy sauce", "sesame oil"],
    ingredients: [
      "3 cups cooked rice",
      "2 cups mixed veg",
      "2 garlic cloves",
      "2 tbsp soy sauce",
      "optional cubed tofu",
    ],
    steps: [
      "Stir-fry garlic and veg on high heat.",
      "Add rice, breaking clumps, and toss until hot.",
      "Season with soy and a drop of sesame oil.",
    ],
    notes: "Skip the usual egg. Cold rice fries better than fresh. Lunchbox-friendly once cool.",
    packable: true,
  },
  {
    id: "chana-masala",
    name: "Tomato chana masala",
    description: "Chickpeas in a thick onion-tomato gravy — pantry dinner that feels like a plan.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 35,
    uses: ["chickpeas", "onion", "tomato", "garlic", "ginger", "spinach"],
    staples: ["garam masala", "cumin", "turmeric"],
    ingredients: [
      "2 cups cooked chickpeas",
      "1 onion, 2 tomatoes",
      "garlic and ginger",
      "1 tsp garam masala, cumin, turmeric",
    ],
    steps: [
      "Brown onion, then garlic and ginger.",
      "Add tomatoes and spices; cook until jammy.",
      "Stir in chickpeas with a splash of water and simmer 10 minutes.",
    ],
    notes: "Serve with rice or bread. Freezes well. No cream, no egg.",
    packable: false,
  },
  {
    id: "dal-tadka",
    name: "Everyday dal tadka",
    description: "Lentils simmered until creamy, finished with cumin and garlic.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["lentils", "dal", "onion", "tomato", "garlic", "spinach"],
    staples: ["red lentils or toor dal", "cumin", "turmeric"],
    ingredients: [
      "1 cup lentils",
      "1 onion, 1 tomato",
      "3 garlic cloves",
      "1 tsp cumin and turmeric",
    ],
    steps: [
      "Simmer lentils with turmeric until soft.",
      "Sauté onion, garlic, and tomato; add to dal.",
      "Bloom cumin in a little oil and pour over the top.",
    ],
    notes: "If you only have canned lentils, shorten the simmer. Rice on the side.",
    packable: false,
  },
  {
    id: "palak-paneer",
    name: "Weeknight palak paneer",
    description: "Spinach gravy with cubes of paneer — dairy-friendly, fully eggless.",
    cuisine: "Indian",
    mealTypes: ["lunch", "dinner"],
    diets: V,
    timeMin: 35,
    uses: ["spinach", "paneer", "onion", "tomato", "garlic", "ginger"],
    staples: ["garam masala", "cumin"],
    ingredients: [
      "a big bunch of spinach",
      "200 g paneer",
      "1 onion, 1 tomato",
      "garlic, ginger, garam masala",
    ],
    steps: [
      "Wilt spinach, then blend with a splash of water.",
      "Sauté onion, tomato, and spices.",
      "Add spinach puree and paneer; simmer 5 minutes.",
    ],
    notes: "No cream required. Tofu stands in for a vegan version.",
    packable: false,
  },
  {
    id: "aloo-paratha-style",
    name: "Skillet aloo mash wraps",
    description: "Spiced potato filling tucked into whatever flatbread you have.",
    cuisine: "Indian",
    mealTypes: ["breakfast", "lunch", "lunchbox"],
    diets: VE,
    timeMin: 25,
    uses: ["potato", "onion", "bread", "tortilla", "chili", "peas"],
    staples: ["cumin", "garam masala"],
    ingredients: [
      "3 potatoes, boiled and mashed",
      "1/2 onion, chopped",
      "cumin and garam masala",
      "4 tortillas or leftover roti",
    ],
    steps: [
      "Mix mash with onion and spices.",
      "Spread on bread and fold.",
      "Toast in a dry pan until both sides spot.",
    ],
    notes: "Packs well for school. Cool before wrapping so it doesn't steam soggy.",
    packable: true,
  },
  {
    id: "pasta-pomodoro",
    name: "Tomato garlic pasta",
    description: "A 20-minute Italian bowl: tomatoes, garlic, pasta, and a little cheese if you have it.",
    cuisine: "Italian",
    mealTypes: ["lunch", "dinner"],
    diets: V,
    timeMin: 25,
    uses: ["tomato", "garlic", "onion", "basil", "cheese", "spinach"],
    staples: ["dried pasta", "olive oil", "chili flakes"],
    ingredients: [
      "250 g dried pasta (egg-free)",
      "4 tomatoes or 1 can",
      "3 garlic cloves",
      "olive oil and chili flakes",
      "optional grated cheese",
    ],
    steps: [
      "Boil egg-free pasta in salted water.",
      "Sizzle garlic in oil, add tomatoes, and simmer.",
      "Toss pasta in the sauce with a splash of cooking water.",
    ],
    notes: "Use egg-free pasta, not egg noodles. If pasta is missing, use rice or zucchini ribbons.",
    packable: false,
  },
  {
    id: "minestrone",
    name: "Fridge minestrone",
    description: "A vegetable soup that uses odds and ends, finished with beans and pasta or rice.",
    cuisine: "Italian",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["carrot", "onion", "celery", "tomato", "beans", "spinach", "zucchini"],
    staples: ["dried pasta or rice", "oregano"],
    ingredients: [
      "onion, carrot, and whatever veg",
      "1 can tomatoes",
      "1 can beans",
      "handful pasta or leftover rice",
      "oregano",
    ],
    steps: [
      "Sauté onion and carrot.",
      "Add tomatoes, water, beans, and veg; simmer 20 minutes.",
      "Stir in pasta until tender.",
    ],
    notes: "Choose short egg-free pasta. Excellent next-day lunch.",
    packable: false,
  },
  {
    id: "caprese-box",
    name: "Caprese lunchbox",
    description: "Tomatoes, cheese, and bread packed as a not-soggy school or work box.",
    cuisine: "Italian",
    mealTypes: ["lunch", "lunchbox"],
    diets: V,
    timeMin: 10,
    uses: ["tomato", "cheese", "mozzarella", "bread", "basil"],
    staples: ["olive oil"],
    ingredients: [
      "2 tomatoes",
      "cheese you have, cubed",
      "bread or crackers",
      "olive oil pinch of salt",
    ],
    steps: [
      "Cube tomato and cheese; keep bread separate.",
      "Pack oil in a tiny container if you can.",
      "Assemble just before eating so bread stays crisp.",
    ],
    notes: "Packing tip: wrap bread in a dry napkin. No mayo, no egg.",
    packable: true,
  },
  {
    id: "bean-tacos",
    name: "Smoky bean tacos",
    description: "Cumin-scented beans, salsa-ish tomatoes, and tortillas — weeknight Mexican.",
    cuisine: "Mexican",
    mealTypes: ["lunch", "dinner", "lunchbox"],
    diets: VE,
    timeMin: 25,
    uses: ["beans", "chickpeas", "tomato", "onion", "avocado", "lettuce", "cheese"],
    staples: ["tortillas", "cumin", "chili powder"],
    ingredients: [
      "2 cups beans",
      "1 onion, 2 tomatoes",
      "1 tsp cumin",
      "8 tortillas",
      "optional avocado",
    ],
    steps: [
      "Sauté onion, add beans, cumin, and a splash of water; mash slightly.",
      "Warm tortillas.",
      "Fill with beans, tomato, and whatever crunchy bits you have.",
    ],
    notes: "Lunchbox: pack fillings and tortillas apart. No sour-cream-only richness required.",
    packable: true,
  },
  {
    id: "quesadilla",
    name: "Veggie cheese quesadilla",
    description: "Crisp tortilla, melted cheese, and leftover vegetables. Ten minutes, one pan.",
    cuisine: "Mexican",
    mealTypes: ["lunch", "snack", "lunchbox"],
    diets: V,
    timeMin: 10,
    uses: ["tortilla", "cheese", "spinach", "pepper", "onion", "beans"],
    staples: ["tortillas"],
    ingredients: [
      "4 tortillas",
      "1 cup grated cheese",
      "handful leftover veg",
    ],
    steps: [
      "Scatter cheese and veg on a tortilla.",
      "Top with a second tortilla and toast both sides.",
      "Rest one minute, then slice.",
    ],
    notes: "Cool before packing so cheese sets. No egg wash on the edges.",
    packable: true,
  },
  {
    id: "veg-chili",
    name: "One-pot veg chili",
    description: "Beans, tomatoes, and chili warmth. Makes leftovers on purpose.",
    cuisine: "American",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["beans", "tomato", "onion", "pepper", "corn", "carrot"],
    staples: ["chili powder", "cumin"],
    ingredients: [
      "2 cans beans",
      "1 can tomatoes",
      "onion and pepper",
      "chili powder and cumin",
    ],
    steps: [
      "Sauté onion and pepper.",
      "Add tomatoes, beans, spices, and a cup of water.",
      "Simmer 20 minutes until thick.",
    ],
    notes: "Repeats well across a week. Eat with rice or bread.",
    packable: false,
  },
  {
    id: "grilled-cheese",
    name: "Tomato grilled cheese",
    description: "The American classic with sliced tomato inside, pan-toasted in a little oil.",
    cuisine: "American",
    mealTypes: ["lunch", "snack"],
    diets: V,
    timeMin: 12,
    uses: ["bread", "cheese", "tomato"],
    staples: [],
    ingredients: [
      "4 slices bread",
      "cheese slices or grated cheese",
      "tomato slices",
    ],
    steps: [
      "Layer cheese and tomato between bread.",
      "Toast in a lightly oiled pan until gold.",
      "Rest 1 minute so the cheese settles.",
    ],
    notes: "Butter is nice; oil works. No egg wash.",
    packable: false,
  },
  {
    id: "veg-stirfry",
    name: "Garlic veg stir-fry",
    description: "High-heat vegetables with soy. Serve over rice or noodles.",
    cuisine: "Chinese",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 20,
    uses: ["broccoli", "pepper", "carrot", "cabbage", "garlic", "tofu", "mushroom"],
    staples: ["soy sauce", "cornstarch"],
    ingredients: [
      "4 cups chopped veg",
      "optional tofu",
      "3 garlic cloves",
      "2 tbsp soy sauce",
    ],
    steps: [
      "Sear tofu if using; set aside.",
      "Stir-fry veg and garlic on high heat.",
      "Add soy and a splash of water; toss tofu back in.",
    ],
    notes: "If you don't have cornstarch, skip the glaze — it still tastes good.",
    packable: false,
  },
  {
    id: "mapo-tofu-veg",
    name: "Gentle mapo-style tofu",
    description: "Soft tofu in a chili-bean sauce without minced meat.",
    cuisine: "Chinese",
    mealTypes: ["dinner"],
    diets: VE,
    timeMin: 25,
    uses: ["tofu", "garlic", "ginger", "scallion", "mushroom"],
    staples: ["soy sauce", "chili bean paste or chili flakes"],
    ingredients: [
      "400 g tofu",
      "garlic and ginger",
      "soy sauce and chili paste",
      "mushrooms if you have them",
    ],
    steps: [
      "Sauté garlic, ginger, and mushrooms.",
      "Add soy, chili, and a little water.",
      "Slide in tofu and simmer gently.",
    ],
    notes: "Traditionally pork; mushrooms keep it vegetarian. Rice is essential.",
    packable: false,
  },
  {
    id: "pad-thai-tofu",
    name: "Tamarind-less tofu pad Thai",
    description: "Rice noodles, tofu, and a lime-soy stand-in sauce when tamarind is missing.",
    cuisine: "Thai",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["tofu", "carrot", "onion", "lime", "lemon", "peanut", "cabbage"],
    staples: ["rice noodles", "soy sauce", "brown sugar"],
    ingredients: [
      "200 g rice noodles",
      "200 g tofu",
      "carrot and onion",
      "lime, soy, a pinch of sugar",
    ],
    steps: [
      "Soak noodles until flexible.",
      "Stir-fry tofu and veg.",
      "Add noodles, soy, sugar, and lime; toss fast.",
    ],
    notes: "No egg scramble. If rice noodles are out, use spaghetti and call it honest.",
    packable: false,
  },
  {
    id: "thai-curry",
    name: "Coconut veg curry",
    description: "A Thai-leaning coconut curry that flexes around whatever vegetables you scanned.",
    cuisine: "Thai",
    mealTypes: ["dinner"],
    diets: VE,
    timeMin: 35,
    uses: ["coconut milk", "pepper", "potato", "carrot", "spinach", "tofu", "broccoli"],
    staples: ["curry paste or curry powder", "coconut milk", "rice"],
    ingredients: [
      "1 can coconut milk",
      "3 cups mixed veg",
      "2 tbsp curry paste or powder",
      "tofu optional",
    ],
    steps: [
      "Fry paste in a little oil until fragrant.",
      "Add coconut milk and veg; simmer until tender.",
      "Season with salt and a squeeze of lime if you have it.",
    ],
    notes: "No fish sauce. Serve over rice. Mild enough for kids if you go easy on chili.",
    packable: false,
  },
  {
    id: "onigiri-box",
    name: "Seasoned rice onigiri box",
    description: "Salted rice balls with a veg filling — travels at room temp.",
    cuisine: "Japanese",
    mealTypes: ["lunch", "lunchbox"],
    diets: VE,
    timeMin: 20,
    uses: ["rice", "cucumber", "carrot", "avocado", "tofu"],
    staples: ["soy sauce", "nori or sesame seeds"],
    ingredients: [
      "2 cups cooked rice",
      "salt",
      "a filling: cucumber, leftover beans, or tofu",
      "soy for dipping",
    ],
    steps: [
      "Season warm rice with salt.",
      "Shape around a teaspoon of filling.",
      "Pack with cut veg on the side.",
    ],
    notes: "Packing tip: wrap each ball so they don't dry out. No fish flakes needed.",
    packable: true,
  },
  {
    id: "veg-katsu-bowl",
    name: "Crispy tofu rice bowl",
    description: "Pan-fried tofu over rice with a quick sweet-soy drizzle.",
    cuisine: "Japanese",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 25,
    uses: ["tofu", "rice", "cabbage", "carrot"],
    staples: ["soy sauce", "flour"],
    ingredients: [
      "300 g tofu",
      "cooked rice",
      "shredded cabbage",
      "soy and a pinch of sugar",
    ],
    steps: [
      "Press tofu, dust with flour, and pan-fry until gold.",
      "Stir soy and sugar for a drizzle.",
      "Serve over rice with cabbage.",
    ],
    notes: "No egg wash for the crust — flour only. Panko if you have it.",
    packable: false,
  },
  {
    id: "greek-bowl",
    name: "Lemon chickpea Greek bowl",
    description: "Chickpeas, cucumber, tomato, and yogurt-tahini if you keep it.",
    cuisine: "Mediterranean",
    mealTypes: ["lunch", "dinner", "lunchbox"],
    diets: V,
    timeMin: 15,
    uses: ["chickpeas", "cucumber", "tomato", "onion", "yogurt", "lemon", "olive"],
    staples: ["oregano", "olive oil"],
    ingredients: [
      "2 cups chickpeas",
      "cucumber, tomato, onion",
      "yogurt",
      "lemon and oregano",
    ],
    steps: [
      "Toss chickpeas with lemon, oil, and oregano.",
      "Chop the salad veg.",
      "Spoon yogurt on the side as a sauce.",
    ],
    notes: "Packing tip: keep yogurt in a separate cup. No feta required.",
    packable: true,
  },
  {
    id: "shakshuka-no",
    name: "Spiced tomato egg-free skillet",
    description: "Mediterranean peppers and tomatoes with chickpeas instead of eggs.",
    cuisine: "Mediterranean",
    mealTypes: ["breakfast", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["tomato", "pepper", "onion", "chickpeas", "spinach"],
    staples: ["paprika", "cumin"],
    ingredients: [
      "tomatoes and peppers",
      "1 onion",
      "1 can chickpeas",
      "paprika and cumin",
    ],
    steps: [
      "Cook onion and pepper until sweet.",
      "Add tomatoes and spices; simmer.",
      "Stir in chickpeas and heat through.",
    ],
    notes: "Bread for scooping. Fully eggless.",
    packable: false,
  },
  {
    id: "hummus-box",
    name: "Hummus and crunch box",
    description: "Homemade-fast hummus from canned chickpeas plus raw veg sticks.",
    cuisine: "Middle Eastern",
    mealTypes: ["lunch", "snack", "lunchbox"],
    diets: VE,
    timeMin: 10,
    uses: ["chickpeas", "lemon", "garlic", "carrot", "cucumber", "pepper"],
    staples: ["tahini or olive oil"],
    ingredients: [
      "1 can chickpeas",
      "1 garlic clove",
      "lemon juice",
      "carrot and cucumber sticks",
    ],
    steps: [
      "Mash or blend chickpeas with lemon, garlic, and oil or tahini.",
      "Cut veg into sticks.",
      "Pack hummus in a small pot with veg around it.",
    ],
    notes: "If tahini is missing, extra oil and a spoon of yogurt (not vegan) still works.",
    packable: true,
  },
  {
    id: "falafel-wrap",
    name: "Oven falafel wraps",
    description: "Chickpea patties baked, not fried, tucked into bread with salad.",
    cuisine: "Middle Eastern",
    mealTypes: ["lunch", "dinner", "lunchbox"],
    diets: VE,
    timeMin: 35,
    uses: ["chickpeas", "onion", "garlic", "parsley", "bread", "tomato", "cucumber"],
    staples: ["cumin", "flour"],
    ingredients: [
      "2 cups chickpeas",
      "onion and garlic",
      "cumin",
      "flour to bind (no egg)",
      "bread or pita",
    ],
    steps: [
      "Pulse chickpeas with onion, garlic, and cumin; bind with flour.",
      "Shape patties and bake or pan-fry.",
      "Wrap with tomato and cucumber.",
    ],
    notes: "Flour binds instead of egg. Packing tip: wrap tight in parchment.",
    packable: true,
  },
  {
    id: "bibimbap",
    name: "Veggie bibimbap",
    description: "Rice with seasoned vegetables and a gochujang drizzle — tofu instead of a fried egg.",
    cuisine: "Korean",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 35,
    uses: ["rice", "spinach", "carrot", "cucumber", "mushroom", "tofu"],
    staples: ["gochujang or chili paste", "sesame oil", "soy sauce"],
    ingredients: [
      "cooked rice",
      "3 kinds of veg, quickly sautéed",
      "tofu",
      "gochujang thinned with water",
    ],
    steps: [
      "Cook each veg quickly with a pinch of salt.",
      "Pan-fry tofu.",
      "Arrange over rice and drizzle sauce.",
    ],
    notes: "The usual fried egg is skipped. Sesame oil is worth asking about.",
    packable: false,
  },
  {
    id: "kimbap-veg",
    name: "Veggie kimbap rolls",
    description: "Rice rolls with carrot, cucumber, and pickled bits — school-lunch gold.",
    cuisine: "Korean",
    mealTypes: ["lunch", "lunchbox"],
    diets: VE,
    timeMin: 30,
    uses: ["rice", "carrot", "cucumber", "spinach", "tofu"],
    staples: ["nori sheets", "sesame oil"],
    ingredients: [
      "2 cups seasoned rice",
      "carrot and cucumber sticks",
      "spinach or tofu strips",
      "nori",
    ],
    steps: [
      "Season rice with a drop of sesame oil and salt.",
      "Lay fillings on nori and rice; roll tight.",
      "Slice with a wet knife after a 5-minute rest.",
    ],
    notes: "Packing tip: slice at home so little hands can eat without mess. No fish cake, no egg strip.",
    packable: true,
  },
  {
    id: "kimchi-fried-rice",
    name: "Kimchi fried rice (tofu)",
    description: "Tangy, spicy fried rice. Tofu instead of spam or egg.",
    cuisine: "Korean",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 20,
    uses: ["rice", "kimchi", "onion", "tofu", "scallion"],
    staples: ["gochujang", "soy sauce"],
    ingredients: [
      "3 cups cooked rice",
      "1 cup kimchi, chopped",
      "tofu cubes",
      "soy sauce",
    ],
    steps: [
      "Sauté kimchi and onion.",
      "Add tofu, then rice.",
      "Season with soy and a dab of gochujang.",
    ],
    notes: "If kimchi is not in the fridge photo, we'll ask. Vegan kimchi if you avoid fish sauce.",
    packable: false,
  },
  {
    id: "mejadra",
    name: "Lentils and rice with onions",
    description: "A Middle Eastern pot of lentils, rice, and sweet fried onions.",
    cuisine: "Middle Eastern",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["lentils", "rice", "onion"],
    staples: ["cumin", "cinnamon"],
    ingredients: [
      "1 cup lentils",
      "1 cup rice",
      "2 onions",
      "cumin",
    ],
    steps: [
      "Cook lentils until almost tender.",
      "Add rice, water, and cumin; steam until done.",
      "Fry onions until dark gold and pile on top.",
    ],
    notes: "Budget hero. Repeats well across a week without feeling sad.",
    packable: false,
  },
  {
    id: "mac-cheese",
    name: "Stovetop mac and cheese",
    description: "One-pot pasta with a simple cheese sauce — egg-free pasta only.",
    cuisine: "American",
    mealTypes: ["lunch", "dinner"],
    diets: V,
    timeMin: 20,
    uses: ["cheese", "milk", "butter"],
    staples: ["short pasta (egg-free)", "flour"],
    ingredients: [
      "250 g short pasta",
      "1 cup milk",
      "1 cup grated cheese",
      "1 tbsp flour",
    ],
    steps: [
      "Cook pasta; save a little water.",
      "Make a quick flour-milk sauce.",
      "Melt in cheese and toss pasta.",
    ],
    notes: "Confirm egg-free pasta. Mustard pinch if you have it, never egg yolk.",
    packable: false,
  },
  {
    id: "pancake-banana",
    name: "Banana skillet pancakes",
    description: "Eggless pancakes using banana and flour — weekend-feeling breakfast.",
    cuisine: "American",
    mealTypes: ["breakfast"],
    diets: V,
    timeMin: 20,
    uses: ["banana", "milk", "flour"],
    staples: ["flour", "baking powder"],
    ingredients: [
      "1 ripe banana",
      "1 cup flour",
      "1 cup milk",
      "1 tsp baking powder",
    ],
    steps: [
      "Mash banana and whisk with milk, flour, and baking powder.",
      "Cook spoons of batter in a lightly oiled pan.",
      "Flip when bubbles set.",
    ],
    notes: "Banana binds instead of egg. Vegan with oat milk.",
    packable: false,
  },
  {
    id: "idli-upma-style",
    name: "Savory leftover rice upma",
    description: "South-Indian-leaning stir of leftover rice with mustard seeds and veg.",
    cuisine: "Indian",
    mealTypes: ["breakfast", "lunch"],
    diets: VE,
    timeMin: 15,
    uses: ["rice", "onion", "peas", "carrot", "chili"],
    staples: ["mustard seeds", "turmeric"],
    ingredients: [
      "3 cups cooked rice",
      "onion and mixed veg",
      "mustard seeds and turmeric",
    ],
    steps: [
      "Pop mustard seeds in oil.",
      "Sauté onion and veg.",
      "Add rice and turmeric; toss until hot.",
    ],
    notes: "Uses scanned leftover rice early in a plan, as promised.",
    packable: false,
  },
  {
    id: "spring-rolls-fresh",
    name: "Fresh veg rolls",
    description: "Rice-paper or lettuce wraps with crunchy filling — no frying.",
    cuisine: "Thai",
    mealTypes: ["lunch", "snack", "lunchbox"],
    diets: VE,
    timeMin: 20,
    uses: ["lettuce", "carrot", "cucumber", "tofu", "pepper", "rice"],
    staples: ["rice paper or large lettuce leaves", "soy sauce"],
    ingredients: [
      "lettuce leaves or rice paper",
      "carrot, cucumber, optional tofu",
      "soy for dipping",
    ],
    steps: [
      "Cut filling into matchsticks.",
      "Roll tight in leaves or soaked rice paper.",
      "Pack dip separately.",
    ],
    notes: "Packing tip: wrap individually so they don't stick. Not smelly, not messy.",
    packable: true,
  },
  {
    id: "pho-ish",
    name: "Quick star-anise veg broth",
    description: "A Vietnamese-leaning noodle soup with whatever greens you have.",
    cuisine: "Chinese",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 30,
    uses: ["onion", "ginger", "mushroom", "spinach", "tofu", "carrot"],
    staples: ["rice noodles", "soy sauce", "star anise or cinnamon"],
    ingredients: [
      "onion and ginger",
      "mushrooms",
      "rice noodles",
      "soy sauce",
      "tofu",
    ],
    steps: [
      "Simmer onion, ginger, and spice in water 15 minutes.",
      "Add mushrooms and tofu.",
      "Pour over soaked noodles.",
    ],
    notes: "No beef bones. Cinnamon stick if star anise is missing.",
    packable: false,
  },
  {
    id: "ratatouille",
    name: "One-pan summer veg stew",
    description: "Mediterranean vegetables collapsed into a spoonable stew.",
    cuisine: "Mediterranean",
    mealTypes: ["lunch", "dinner"],
    diets: VE,
    timeMin: 40,
    uses: ["zucchini", "eggplant", "tomato", "pepper", "onion", "garlic"],
    staples: ["olive oil", "oregano"],
    ingredients: [
      "zucchini, eggplant, or both",
      "tomatoes and onion",
      "garlic and oregano",
    ],
    steps: [
      "Sauté onion and garlic.",
      "Add chunked veg and tomatoes.",
      "Simmer until silky, 25 minutes.",
    ],
    notes: "Eat with bread or rice. Better the next day.",
    packable: false,
  },
  {
    id: "breakfast-burrito",
    name: "Potato breakfast burrito",
    description: "Spiced potatoes, beans, and salsa in a wrap — scrambled tofu, not eggs.",
    cuisine: "Mexican",
    mealTypes: ["breakfast", "lunch"],
    diets: VE,
    timeMin: 25,
    uses: ["potato", "beans", "tortilla", "onion", "tomato", "tofu"],
    staples: ["tortillas", "cumin"],
    ingredients: [
      "2 potatoes, diced",
      "beans",
      "optional crumbled tofu",
      "tortillas",
    ],
    steps: [
      "Pan-fry potatoes with cumin until crisp.",
      "Warm beans and tofu.",
      "Wrap with tomato salsa.",
    ],
    notes: "Tofu scramble replaces eggs. Freeze extra wraps.",
    packable: true,
  }
];
